Repository elastic/e2e-testing, pull requests merged in 2019-09, with the labels that each got.

#18 fix: pre-commit requirements
  .ci/Jenkinsfile
  .ci/scripts/install-dependencies.sh
  cli/config/config.go
  cli/config/config_test.go
Labels: automation, bug

#25 fix: gometalinter got issues with go modules
  .ci/scripts/install-dependencies.sh
Labels: automation, bug

#28 (#27) upgrade test containers
  cli/go.mod
  cli/go.sum
  metricbeat-tests/go.mod
  metricbeat-tests/go.sum
Labels: automation

#24 (#23) Document functional tests
  .vscode/launch.json
  cli/.gitignore
  metricbeat-tests/README.md
Labels: automation

#29 (#22) Simplify searchResult interface
  metricbeat-tests/elasticsearch.go
  metricbeat-tests/runner_test.go
Labels: automation

#33 Bug fixes
  cli/config/config.go
  cli/services/service.go
  metricbeat-tests/.gitignore
  metricbeat-tests/runner_test.go
Labels: automation, bug

#34 fix pre-commit hooks in the CI
  .ci/Jenkinsfile
  .ci/scripts/install-dependencies.sh
  .gitignore
  .pre-commit-config.yaml
Labels: automation, enhancement

#39 ci(jenkins): golangci-lint
  .pre-commit-config.yaml
Labels: automation, enhancement

#40 chore: add build status in the README.md
  README.md
Labels: automation, enhancement

#38 (#37) Honor Godog's life cycle hooks (Before/After Scenario)
  .vscode/launch.json
  cli/services/service.go
  cli/services/service_test.go
  metricbeat-tests/README.md
  metricbeat-tests/apache_test.go
  metricbeat-tests/assertions.go
  metricbeat-tests/elasticsearch.go
  metricbeat-tests/go.mod
  metricbeat-tests/go.sum
  metricbeat-tests/metricbeat.go
  metricbeat-tests/mysql_test.go
  metricbeat-tests/redis_test.go
  metricbeat-tests/runner_test.go
  metricbeat-tests/service_common_test.go
Labels: automation

#48 (#44) Better management when cleaning up test resources
  cli/services/manager.go
  metricbeat-tests/features/apache.feature
  metricbeat-tests/features/mysql.feature
  metricbeat-tests/features/redis.feature
  metricbeat-tests/go.mod
  metricbeat-tests/metricbeat.go
  metricbeat-tests/runner_test.go
  metricbeat-tests/service_common_test.go
Labels: automation, bug
