Repository elastic/e2e-testing, pull requests merged in 2019-08, with the labels that each got.

#2 fix: stashed scripts should be created in the checkout stage
  .ci/Jenkinsfile
Labels: automation, bug

#3 fix: 8.0.0 has not been released yet
  .ci/scripts/tag-metricbeats.sh
  features/apache.feature
  features/mysql.feature
Labels: automation, bug

#5 Enable feature selector on test scripts
  .ci/Jenkinsfile
  .ci/scripts/functional-test.sh
  Makefile
Labels: automation

#9 feat: use the pre-commit hooks library
  .ci/scripts/gherkin-lint.sh
  .pre-commit-config.yaml
Labels: automation, enhancement

#10 Add a script that builds the binaries for all platforms
  .ci/.package.yaml
  .ci/Jenkinsfile
  .gitignore
  VERSION.txt
  build.sh
Labels: automation, enhancement

#13 ci(jenkins): simplify the parameters in the functional tests pipeline
  .ci/functionalTests.groovy
Labels: automation, enhancement

#16 Improve Logging using logrus as library
  cli/.gitignore
  cli/README.md
  cli/cmd/root.go
  cli/cmd/run.go
  cli/cmd/stop.go
  cli/config/config.go
  cli/config/config_test.go
  cli/docker/docker.go
  cli/go.mod
  cli/go.sum
  cli/log/logger.go
  cli/services/manager.go
  cli/services/service.go
  metricbeat-tests/go.mod
  metricbeat-tests/go.sum
  metricbeat-tests/metricbeat.go
  metricbeat-tests/runner_test.go
Labels: automation

#20 First functional tests against a running stack
  .ci/functionalTests.groovy
  .ci/scripts/functional-test.sh
  cli/cmd/run.go
  cli/docker/docker.go
  cli/services/service.go
  cli/services/service_test.go
  metricbeat-tests/Makefile
  metricbeat-tests/apache_test.go
  metricbeat-tests/configurations/apache.yml
  metricbeat-tests/configurations/mysql.yml
  metricbeat-tests/configurations/redis.yml
  metricbeat-tests/elasticsearch.go
  metricbeat-tests/features/apache.feature
  metricbeat-tests/features/mysql.feature
  metricbeat-tests/features/redis.feature
  metricbeat-tests/go.mod
  metricbeat-tests/go.sum
  metricbeat-tests/metricbeat.go
  metricbeat-tests/mysql_test.go
  metricbeat-tests/outputs/.touch
  metricbeat-tests/redis_test.go
  metricbeat-tests/runner_test.go
Labels: automation, enhancement
