Repository elastic/e2e-testing, pull requests merged in 2020-10, with the labels that each got.

#337 chore: move wait for kibana method to the client
  cli/NOTICE.txt
  cli/go.mod
  cli/go.sum
  cli/services/kibana.go
  cli/services/kibana_test.go
  e2e/_suites/ingest-manager/ingest-manager_test.go
  e2e/kibana.go
Labels: needs_backport

#344 chore: move wait for kibana method to the client (#337) backport for 7.9.x
  cli/NOTICE.txt
  cli/go.mod
  cli/go.sum
  cli/services/kibana.go
  cli/services/kibana_test.go
  e2e/_suites/ingest-manager/ingest-manager_test.go
  e2e/kibana.go
Labels: backport

#312 refactor to agent deploy scenario reduce run time
  e2e/_suites/ingest-manager/features/fleet_mode_agent.feature
Labels: Team: Ingest Management

#356 [7.9.x] Reduce run time
  e2e/_suites/ingest-manager/features/fleet_mode_agent.feature
Labels: backport

#357 chore: add make goals to clean up local workspace and docker (#354) backport for 7.9.x
  .ci/scripts/clean-docker.sh
  Makefile
  e2e/_suites/ingest-manager/README.md
  e2e/_suites/metricbeat/README.md
Labels: backport

#348 chore: rename ingest_manager endpoints to fleet
  .ci/.e2e-tests.yaml
  .ci/Jenkinsfile
  .ci/e2eTestingFleetDaily.groovy
  .ci/jobs/e2e-testing-fleet-daily-mbp.yml
  .github/paths-labeller.yml
  README.md
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/services/kibana.go
  e2e/_suites/fleet/README.md
  e2e/_suites/fleet/configurations/kibana.config.yml
  e2e/_suites/fleet/features/agent_endpoint_integration.feature
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/features/stand_alone_agent.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/fleet/integrations.go
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/stand-alone.go
Labels: needs_backport

#360 fix: preset default values for stack and metricbeat
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  e2e/Makefile
Labels: needs_backport

#361 fix: preset default values for stack and metricbeat (#360) backport for 7.9.x
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  e2e/Makefile
Labels: backport

#362 fix: rename JJB files in maintenance branch too
  .ci/e2eTestingFleetDaily.groovy
  .ci/jobs/e2e-testing-fleet-daily-mbp.yml
Labels: automation, bug

#363 [CI] Use user-pass credentials
  .ci/Jenkinsfile
Labels: automation

#369 fix: do not pass TRACE log level to metricbeat (#366) backport for 7.9.x
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#370 fix: use base version for metricbeat (#368) backport for 7.9.x
  e2e/Makefile
  e2e/_suites/ingest-manager/services.go
  e2e/_suites/ingest-manager/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#372 fix: use policy instead of config
  e2e/_suites/ingest-manager/fleet.go
Labels: bug

#381 chore: remove orphan containers when shutting down the compose
  cli/services/manager.go
Labels: needs_backport

#383 chore: use the enriched slack message from the shared library
  .ci/Jenkinsfile
Labels: automation

#384 fix: proper variable interpolation
  .ci/Jenkinsfile
Labels: bug

#382 chore: remove orphan containers when shutting down the compose (#381) backport for 7.9.x
  cli/services/manager.go
Labels: backport

#386 chore: use the enriched slack mesage from the shared library (#383) | fix: proper variable interpolation (#384) backport for 7.9.x
  .ci/Jenkinsfile
Labels: backport

#390 fix: wrong variable name
  .ci/Jenkinsfile
Labels: bug, needs_backport

#391 fix: wrong variable name (#390) backport for 7.10.x
  .ci/Jenkinsfile
Labels: backport

#392 fix: wrong variable name (#390) backport for 7.9.x
  .ci/Jenkinsfile
Labels: backport

#393 fix: double down the timeout to check security events (#389) backport for 7.10.x
  e2e/_suites/fleet/fleet.go
Labels: backport

#394 fix: double down the timeout to check security events (#389) backport for 7.9.x
  e2e/_suites/ingest-manager/fleet.go
Labels: backport

#398 chore: use URL parameter to avoid adding test stats
  e2e/utils.go
Labels: needs_backport

#401 chore: use URL parameter to avoid adding test stats (#398) backport for 7.9.x
  e2e/utils.go
Labels: backport

#400 chore: use URL parameter to avoid adding test stats (#398) backport for 7.10.x
  e2e/utils.go
Labels: backport

#403 fix: use base version to extract the TAR file
  e2e/_suites/fleet/services.go
Labels: enhancement

#406 chore: simplify metricbeat waits
  e2e/_suites/metricbeat/features/apache.feature
  e2e/_suites/metricbeat/features/metricbeat.feature
  e2e/_suites/metricbeat/features/mysql.feature
  e2e/_suites/metricbeat/features/redis.feature
  e2e/_suites/metricbeat/features/vsphere.feature
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: needs_backport
