Repository elastic/e2e-testing, pull requests merged in 2020-11, with the labels that each got.

#129 chore: support for Helm 3
  .ci/Jenkinsfile
  .ci/e2eTestingHelmDaily.groovy
  .ci/scripts/install-helm-test-dependencies.sh
  cli/services/helm.go
  cli/services/kubectl.go
  cli/shell/shell.go
  e2e/_suites/helm/features/apm_server.feature
  e2e/_suites/helm/helm_charts_test.go
Labels: automation, needs_backport

#415 chore: support for Helm 3 (#129) backport for 7.10.x
  .ci/Jenkinsfile
  .ci/e2eTestingHelmDaily.groovy
  .ci/scripts/install-helm-test-dependencies.sh
  cli/services/helm.go
  cli/services/kubectl.go
  cli/shell/shell.go
  e2e/_suites/helm/features/apm_server.feature
  e2e/_suites/helm/helm_charts_test.go
Labels: backport

#416 chore: support for Helm 3 (#129) backport for 7.9.x
  .ci/Jenkinsfile
  .ci/e2eTestingHelmDaily.groovy
  .ci/scripts/install-helm-test-dependencies.sh
  cli/services/helm.go
  cli/services/kubectl.go
  cli/shell/shell.go
  e2e/_suites/helm/features/apm_server.feature
  e2e/_suites/helm/helm_charts_test.go
Labels: backport

#422 fix: send slack notifications to the proper channel (#421) backport for 7.10.x
  .ci/Jenkinsfile
Labels: backport

#423 fix: send slack notifications to the proper channel (#421) backport for 7.9.x
  .ci/Jenkinsfile
Labels: backport

#427 feat: calculate latest version for Beats (#426) backport for 7.10.x
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/utils.go
Labels: backport

#428 feat: calculate latest version for Beats (#426) backport for 7.9.x
  e2e/_suites/ingest-manager/ingest-manager_test.go
  e2e/_suites/ingest-manager/services.go
  e2e/_suites/ingest-manager/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/utils.go
Labels: backport

#432 chore(ci): fail fast the parallel execution for the e2e tests (#429) backport for 7.9.x
  .ci/Jenkinsfile
Labels: backport

#431 chore(ci): fail fast the parallel execution for the e2e tests (#429) backport for 7.10.x
  .ci/Jenkinsfile
Labels: backport

#434 chore(ci): fail fast the parallel execution for the e2e tests (#429) backport for 7.x
  .ci/Jenkinsfile
Labels: backport

#442 chore: bump major version of Go to 1.14.12
  .ci/Jenkinsfile
  .go-version
  cli/go.mod
  e2e/go.mod
Labels: automation

#446 fix: add EOF to go-version file
  .go-version
Labels: bug

#443 chore: bump major version of Go to 1.14.12 (#442) backport for 7.x
  .ci/Jenkinsfile
  .go-version
  cli/go.mod
  e2e/go.mod
Labels: backport

#444 chore: bump major version of Go to 1.14.12 (#442) backport for 7.10.x
  .ci/Jenkinsfile
  .go-version
  cli/go.mod
  e2e/go.mod
Labels: backport

#447 chore: bump helm-charts + helm version
  .ci/Jenkinsfile
  .ci/scripts/install-helm-test-dependencies.sh
  e2e/_suites/helm/README.md
  e2e/_suites/helm/features/metricbeat.feature
  e2e/_suites/helm/helm_charts_test.go
Labels: helm, needs_backport

#449 chore: bump helm-charts + helm version (#447)
  .ci/Jenkinsfile
  .ci/scripts/install-helm-test-dependencies.sh
  e2e/_suites/helm/README.md
  e2e/_suites/helm/features/metricbeat.feature
  e2e/_suites/helm/helm_charts_test.go
Labels: backport

#450 chore: bump helm-charts + helm version (#447)
  .ci/Jenkinsfile
  .ci/scripts/install-helm-test-dependencies.sh
  e2e/_suites/helm/README.md
  e2e/_suites/helm/features/metricbeat.feature
  e2e/_suites/helm/helm_charts_test.go
Labels: backport

#451 chore: bump helm-charts + helm version (#447)
  .ci/Jenkinsfile
  .ci/scripts/install-helm-test-dependencies.sh
  e2e/_suites/helm/README.md
  e2e/_suites/helm/features/metricbeat.feature
  e2e/_suites/helm/helm_charts_test.go
Labels: backport

#453 fix: apply golint recomendations
  cli/services/helm.go
  cli/services/kubectl.go
  cli/shell/shell_test.go
  e2e/utils.go
Labels: needs_backport

#455 fix: apply golint recomendations (#453) backport for 7.10.x
  cli/services/helm.go
  cli/services/kubectl.go
  cli/shell/shell_test.go
  e2e/utils.go
Labels: backport

#456 fix: apply golint recomendations (#453) backport for 7.9.x
  cli/services/helm.go
  cli/services/kubectl.go
  cli/shell/shell_test.go
  e2e/utils.go
Labels: backport

#454 fix: apply golint recomendations (#453) backport for 7.x
  cli/services/helm.go
  cli/services/kubectl.go
  cli/shell/shell_test.go
  e2e/utils.go
Labels: backport

#460 chore: calculate reporter name from isPR or isBranch (#457) backport for 7.9.x
  .ci/Jenkinsfile
Labels: backport

#459 chore: calculate reporter name from isPR or isBranch (#457) backport for 7.10.x
  .ci/Jenkinsfile
Labels: backport

#458 chore: calculate reporter name from isPR or isBranch (#457) backport for 7.x
  .ci/Jenkinsfile
Labels: backport

#461 chore: double Helm max timeout
  e2e/_suites/helm/helm_charts_test.go
Labels: needs_backport

#463 chore: double Helm max timeout (#461) backport for 7.10.x
  e2e/_suites/helm/helm_charts_test.go
Labels: backport

#464 chore: double Helm max timeout (#461) backport for 7.9.x
  e2e/_suites/helm/helm_charts_test.go
Labels: backport

#465 fix: move evaluation out of post section
  .ci/Jenkinsfile
Labels: automation, bug, needs_backport

#466 fix: move evaluation out of post section (#465) backport for 7.x
  .ci/Jenkinsfile
Labels: backport

#467 fix: move evaluation out of post section (#465) backport for 7.10.x
  .ci/Jenkinsfile
Labels: backport

#468 fix: move evaluation out of post section (#465) backport for 7.9.x
  .ci/Jenkinsfile
Labels: backport

#462 chore: double Helm max timeout (#461) backport for 7.x
  e2e/_suites/helm/helm_charts_test.go
Labels: backport

#470 fix: revert work for calculating reporter based on branch/pr
  .ci/Jenkinsfile
Labels: bug

#471 fix: revert work for calculating reporter based on branch/pr
  .ci/Jenkinsfile
Labels: backport

#478 fix: use full process name to match in pgrep (#475) backport for 7.9.x
  e2e/utils.go
Labels: backport

#476 fix: use full process name to match in pgrep (#475) backport for 7.x
  e2e/utils.go
Labels: backport

#477 fix: use full process name to match in pgrep (#475) backport for 7.10.x
  e2e/utils.go
Labels: backport
