Repository elastic/e2e-testing, pull requests merged in 2020-12, with the labels that each got.

#486 fix: double max timeout when waitin for docs in standalone mode (#483) backport for 7.9.x
  e2e/_suites/ingest-manager/stand-alone.go
Labels: backport

#484 fix: double max timeout when waitin for docs in standalone mode (#483) backport for 7.x
  e2e/_suites/fleet/stand-alone.go
Labels: backport

#485 fix: double max timeout when waitin for docs in standalone mode (#483) backport for 7.10.x
  e2e/_suites/fleet/stand-alone.go
Labels: backport

#487 docs: document how to run regression tests
  e2e/README.md
  e2e/regression-testing.gif
Labels: documentation

#481 fix: update log path for TAR installer
  e2e/_suites/fleet/services.go
Labels: bug

#494 fix: update log path for TAR installer (#481) backport for 7.x
  e2e/_suites/fleet/services.go
Labels: backport

#495 fix: update log path for TAR installer (#481) backport for 7.10.x
  e2e/_suites/fleet/services.go
Labels: backport

#498 fix: exclude images from non-breaking-spaces lint (#497) backport for 7.x
  .pre-commit-config.yaml
Labels: backport

#499 fix: exclude images from non-breaking-spaces lint (#497) backport for 7.10.x
  .pre-commit-config.yaml
Labels: backport

#500 fix: exclude images from non-breaking-spaces lint (#497) backport for 7.9.x
  .pre-commit-config.yaml
Labels: backport

#491 docs: document how to run regression tests (#487) backport for 7.x
  e2e/README.md
  e2e/regression-testing.gif
Labels: backport

#492 docs: document how to run regression tests (#487) backport for 7.10.x
  e2e/README.md
  e2e/regression-testing.gif
Labels: backport

#493 docs: document how to run regression tests (#487) backport for 7.9.x
  e2e/README.md
  e2e/regression-testing.gif
Labels: backport

#504 fix: enhance GCP queries for PRs
  e2e/_suites/fleet/services.go
  e2e/utils.go
Labels: automation, bug

#439 work for issue #379 - adding back rpm and deb tests
  .ci/.e2e-tests.yaml
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/features/stand_alone_agent.feature
Labels: Team: Ingest Management, [zube]: In Progress, automation, enhancement

#508 chore: reduce GCP storage queries filtering by "pull-requests/" prefix (1d2cadba) | chore: enrich logs when querying GCP storage entries (89df4c8c) | chore: fix GCP filename for TAR files (7d4e7f9c) | chore: pass max timeout to the bucket U
  e2e/_suites/fleet/services.go
  e2e/utils.go
Labels: backport

#509 chore: reduce GCP storage queries filtering by "pull-requests/" prefix (1d2cadba) | chore: enrich logs when querying GCP storage entries (89df4c8c) | chore: fix GCP filename for TAR files (7d4e7f9c) | chore: pass max timeout to the bucket U
  e2e/_suites/fleet/services.go
  e2e/utils.go
Labels: backport

#512 chore: refactor integrations supporting tags in examples (9d228984) | fix: add example name (74435c7a) | chore: merge variants into one single feature file (8652d410) backport for 7.9.x
  .ci/.e2e-tests.yaml
  e2e/_suites/metricbeat/features/apache.feature
  e2e/_suites/metricbeat/features/integrations.feature
  e2e/_suites/metricbeat/features/mysql.feature
  e2e/_suites/metricbeat/features/redis.feature
  e2e/_suites/metricbeat/features/vsphere.feature
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#511 chore: refactor integrations supporting tags in examples (9d228984) | fix: add example name (74435c7a) | chore: merge variants into one single feature file (8652d410) backport for 7.10.x
  .ci/.e2e-tests.yaml
  e2e/_suites/metricbeat/features/apache.feature
  e2e/_suites/metricbeat/features/integrations.feature
  e2e/_suites/metricbeat/features/mysql.feature
  e2e/_suites/metricbeat/features/redis.feature
  e2e/_suites/metricbeat/features/vsphere.feature
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#510 chore: refactor integrations supporting tags in examples (9d228984) | fix: add example name (74435c7a) | chore: merge variants into one single feature file (8652d410) backport for 7.x
  .ci/.e2e-tests.yaml
  e2e/_suites/metricbeat/features/apache.feature
  e2e/_suites/metricbeat/features/integrations.feature
  e2e/_suites/metricbeat/features/mysql.feature
  e2e/_suites/metricbeat/features/redis.feature
  e2e/_suites/metricbeat/features/vsphere.feature
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#519 fix: use proper gherkin comments
  e2e/_suites/fleet/features/fleet_mode_agent.feature
Labels: bug

#518 chore: simplify junit report name
  .ci/scripts/functional-test.sh
Labels: automation, bug

#521 [7.10.x] Backport
  .ci/.e2e-tests.yaml
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/features/stand_alone_agent.feature
Labels: backport

#525 chore: simplify junit report name (#518) backport for 7.9.x
  .ci/scripts/functional-test.sh
Labels: backport

#523 chore: simplify junit report name (#518) backport for 7.x
  .ci/scripts/functional-test.sh
Labels: backport

#524 chore: simplify junit report name (#518) backport for 7.10.x
  .ci/scripts/functional-test.sh
Labels: backport

#522 [7.x] Backports
  .ci/.e2e-tests.yaml
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/features/stand_alone_agent.feature
Labels: backport

#531 fix: double quote tags if they are set
  e2e/Makefile
Labels: automation, bug

#536 fix: do not check artifacts API for PRs
  e2e/utils.go
Labels: bug

#537 disable upgrade tests
  e2e/_suites/fleet/features/fleet_mode_agent.feature
Labels: bug

#538 fix: do not check artifacts API for PRs (#536) backport for 7.x
  e2e/utils.go
Labels: backport

#539 fix: do not check artifacts API for PRs (#536) backport for 7.10.x
  e2e/utils.go
Labels: backport

#540 update-to-available-version
  .ci/Jenkinsfile
Labels: Team: Ingest Management

#545 unskip deb and rpm test (#542) backport for 7.10.x
  e2e/_suites/fleet/features/fleet_mode_agent.feature
Labels: backport

#544 unskip deb and rpm test (#542) backport for 7.x
  e2e/_suites/fleet/features/fleet_mode_agent.feature
Labels: backport
