Repository elastic/e2e-testing, pull requests merged in 2021-07, with the labels that each got.

#1312 ci: allow /test trigger
  .ci/Jenkinsfile
Labels: v7.13.0, v7.14.0

#1315 Re-enable docker remote with correct kibana config
  cli/config/compose/profiles/fleet/docker-compose.yml
Labels: v7.13.0, v7.14.0

#1310 Update readmes to reflect using go test instead of godog binary
  e2e/_suites/fleet/README.md
  e2e/_suites/helm/README.md
  e2e/_suites/kubernetes-autodiscover/README.md
  e2e/_suites/metricbeat/README.md
  e2e/commons-test.mk
Labels: documentation, v7.13.0, v7.14.0

#1320 Temporary fix for revoke token tests
  e2e/_suites/fleet/fleet.go
Labels: v7.13.0, v7.14.0

#1062 Bump elastic stack version automation and auto-merge with mergify
  .ci/bump-stack-version.sh
  .gitignore
  .mergify.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
Labels: automation, v7.15.0

#1291 New Scenarios for the System integration test
  .ci/.e2e-tests.yaml
  e2e/_suites/fleet/features/agent_endpoint_integration.feature
  e2e/_suites/fleet/features/system_integration.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/testresources/metrics.json
Labels: Team:Automation, area:test, v7.13.0, v7.14.0, v7.15.0

#1336 fix: apply container name to elastic-agent Docker services
  cli/config/compose/services/elastic-agent/centos/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/debian/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  e2e/_suites/fleet/stand-alone.go
Labels: v7.13.0, v7.14.0, v7.15.0

#1341 chore(ci): be more specific about the underlying ARM OS
  .ci/Jenkinsfile
Labels: v7.13.0, v7.14.0, v7.15.0

#1346 [automation] update elastic stack version for testing 8.0.0-1e9bea0f
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency

#1350 [automation] update elastic stack version for testing 8.0.0-a6334483
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency

#1356 chore: improve the automation for the stack version bump (#1351) backport for 7.14.x
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-aarch64.rpm
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-amd64.deb
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-arm64.deb
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-amd64.docker.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-amd64.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-arm64.docker.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-arm64.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-x86_64.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-x86_64.rpm
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-ubi8-BEATS_VERSION-linux-amd64.docker.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-ubi8-BEATS_VERSION-linux-arm64.docker.tar.gz
  internal/_testresources/gcp/commits.json
  internal/_testresources/gcp/snapshots.json
  internal/utils/utils_test.go
Labels: backport

#1355 chore: improve the automation for the stack version bump (#1351) backport for 7.x
  .ci/bump-stack-version.sh
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-aarch64.rpm
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-amd64.deb
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-arm64.deb
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-amd64.docker.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-amd64.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-arm64.docker.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-arm64.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-x86_64.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-x86_64.rpm
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-ubi8-BEATS_VERSION-linux-amd64.docker.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-ubi8-BEATS_VERSION-linux-arm64.docker.tar.gz
  internal/_testresources/gcp/commits.json
  internal/_testresources/gcp/snapshots.json
  internal/utils/utils_test.go
Labels: backport

#1357 chore: improve the automation for the stack version bump (#1351) backport for 7.13.x
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-aarch64.rpm
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-amd64.deb
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-arm64.deb
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-amd64.docker.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-amd64.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-arm64.docker.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-arm64.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-x86_64.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-x86_64.rpm
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-ubi8-BEATS_VERSION-linux-amd64.docker.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-ubi8-BEATS_VERSION-linux-arm64.docker.tar.gz
  internal/_testresources/gcp/commits.json
  internal/_testresources/gcp/snapshots.json
  internal/utils/utils_test.go
Labels: backport

#1348 fix: expose fleet-server port
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  e2e/_suites/fleet/stand-alone.go
Labels: v7.13.0, v7.14.0, v7.15.0

#1361 Add kubernetes autodiscover scenario with inputs
  e2e/_suites/kubernetes-autodiscover/features/filebeat.feature
  e2e/_suites/kubernetes-autodiscover/testdata/templates/filebeat.yml.tmpl
  internal/kubernetes/kubernetes.go
Labels: Team:Integrations, enhancement, v7.13.0, v7.14.0, v7.15.0

#1368 chore: read elastic-agent logs using native OS' log manager
  internal/installer/base.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/installer/elasticagent_tar_macos.go
  internal/installer/elasticagent_zip.go
  internal/systemd/cmds.go
Labels: v7.13.0, v7.14.0, v7.15.0

#1378 chore: read elastic-agent logs using native OS' log manager (#1368) backport for 7.x
  internal/installer/base.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/installer/elasticagent_tar_macos.go
  internal/installer/elasticagent_zip.go
  internal/systemd/cmds.go
Labels: backport

#1382 feat: add scheduled pipeline for k8s autodiscovery test suite (#1100)
  .ci/e2eTestingK8SAutodiscoveryDaily.groovy
  .ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml
  README.md
Labels: backport

#1383 chore(ci): listen for 7.14 branch, retiring 7.12 (#1300) backport for 7.x
  .backportrc.json
  .ci/jobs/e2e-testing-fleet-daily-mbp.yml
  .ci/jobs/e2e-testing-helm-daily-mbp.yml
  .ci/jobs/e2e-testing-integrations-daily-mbp.yml
  .ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml
  .ci/jobs/e2e-testing-mbp.yml
Labels: backport

#1384 chore(ci): propagate downstream build result to upstream (#1377)
  .ci/e2eKibana.groovy
  .ci/e2eTestingFleetDaily.groovy
  .ci/e2eTestingHelmDaily.groovy
  .ci/e2eTestingIntegrationsDaily.groovy
  .ci/e2eTestingK8SAutodiscoveryDaily.groovy
Labels: backport

#1385 Add test case for add_kubernetes_metadata with autodiscover
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
  e2e/_suites/kubernetes-autodiscover/features/filebeat.feature
  e2e/_suites/kubernetes-autodiscover/testdata/templates/filebeat.yml.tmpl
Labels: Team:Integrations, v7.14.0, v7.15.0

#1349 Fix for the OS field and scenarios
  e2e/_suites/fleet/features/system_integration.feature
  e2e/_suites/fleet/fleet.go
  go.mod
  go.sum
  internal/kibana/agents.go
Labels: v7.13.0, v7.14.0, v7.15.0

#1392 [automation] update elastic stack version for testing 7.15.0-bd471fd6
  .stack-version
Labels: automation, dependency

#1393 fix(ci): wait for downstream jobs on scheduled jobs
  .ci/e2eKibana.groovy
  .ci/e2eTestingFleetDaily.groovy
  .ci/e2eTestingHelmDaily.groovy
  .ci/e2eTestingIntegrationsDaily.groovy
  .ci/e2eTestingK8SAutodiscoveryDaily.groovy
Labels: v7.14.0, v7.15.0

#1148 chore: add APM integration to CI
  .ci/.e2e-tests.yaml
  cli/config/compose/services/elastic-agent/apm-legacy/config/apm-server.yml
  cli/config/compose/services/elastic-agent/apm-legacy/config/capabilities.yml
  cli/config/compose/services/elastic-agent/apm-legacy/config/credentials.yml
  cli/config/compose/services/elastic-agent/apm-legacy/config/fleet-setup.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  e2e/_suites/fleet/features/agent_endpoint_integration.feature
  e2e/_suites/fleet/features/apm_integration.feature
  e2e/_suites/fleet/features/integrations.feature
  e2e/_suites/fleet/features/linux_integration.feature
  e2e/_suites/fleet/features/stand_alone_agent.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/stand-alone.go
  internal/kibana/fleet.go
Labels: Team:Automation, area:test, priority:medium, requested-by:APM, size:M, triaged, v7.13.0, v7.14.0, v7.15.0

#1406 fix: check if the snapshot version contains a commit
  internal/utils/utils.go
  internal/utils/utils_test.go
Labels: v7.13.0, v7.14.0, v7.15.0

#1413 fix: parse hashed version to download artifacts from Elastic
  internal/utils/utils.go
Labels: v7.13.0, v7.14.0, v7.15.0

#1414 chore: bump Go agent to v1.13.0
  go.mod
  go.sum
Labels: v7.13.0, v7.14.0, v7.15.0
