Repository elastic/e2e-testing, pull requests merged in 2021-02, with the labels that each got.

#679 feat: support executing nightly tests on CI (#669) backport for 7.11.x
  .ci/Jenkinsfile
  .ci/e2eTestingFleetDaily.groovy
  e2e/README.md
Labels: backport

#680 feat: support executing nightly tests on CI (#669) backport for 7.10.x
  .ci/Jenkinsfile
  .ci/e2eTestingFleetDaily.groovy
  e2e/README.md
Labels: backport

#681 feat: support executing nightly tests on CI (#669) backport for 6.8.x
  .ci/Jenkinsfile
  .ci/e2eTestingFleetDaily.groovy
  e2e/README.md
Labels: backport

#678 feat: support executing nightly tests on CI (#669) backport for 7.x
  .ci/Jenkinsfile
  .ci/e2eTestingFleetDaily.groovy
  e2e/README.md
Labels: backport

#682 [CI] Change slack channel
  .ci/e2eTestingFleetDaily.groovy
Labels: automation

#684 [CI] Change slack channel (#682) backport for 7.11.x
  .ci/e2eTestingFleetDaily.groovy
Labels: Team:Automation, automation, backport, ci

#685 [CI] Change slack channel (#682) backport for 7.10.x
  .ci/e2eTestingFleetDaily.groovy
Labels: Team:Automation, automation, backport, ci

#686 [CI] Change slack channel (#682) backport for 6.8.x
  .ci/e2eTestingFleetDaily.groovy
Labels: Team:Automation, automation, backport, ci

#683 [CI] Change slack channel (#682) backport for 7.x
  .ci/e2eTestingFleetDaily.groovy
Labels: Team:Automation, automation, backport, ci

#694 feat: support using local Beats repository in the tests (#688) backport for 6.8.x
  e2e/README.md
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/services_test.go
  e2e/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-amd64.deb
  e2e/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-linux-amd64.tar.gz
  e2e/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-x86_64.rpm
Labels: backport

#691 feat: support using local Beats repository in the tests (#688) backport for 7.x
  e2e/README.md
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/services_test.go
  e2e/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-amd64.deb
  e2e/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-linux-amd64.tar.gz
  e2e/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-x86_64.rpm
Labels: backport

#692 feat: support using local Beats repository in the tests (#688) backport for 7.11.x
  e2e/README.md
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/services_test.go
  e2e/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-amd64.deb
  e2e/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-linux-amd64.tar.gz
  e2e/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-x86_64.rpm
Labels: backport

#693 feat: support using local Beats repository in the tests (#688) backport for 7.10.x
  e2e/README.md
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/services_test.go
  e2e/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-amd64.deb
  e2e/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-linux-amd64.tar.gz
  e2e/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-x86_64.rpm
Labels: backport

#700 fix: update method args
  e2e/_suites/fleet/services_test.go
Labels: P1, bug

#696 chore: refactor Fleet upgrade tests (#671) backport for 7.x
  e2e/Makefile
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/services_test.go
Labels: backport

#697 chore: refactor Fleet upgrade tests (#671) backport for 7.11.x
  .ci/Jenkinsfile
  e2e/Makefile
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/services_test.go
Labels: backport

#698 chore: refactor Fleet upgrade tests (#671) backport for 7.10.x
  .ci/Jenkinsfile
  e2e/Makefile
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/services_test.go
Labels: backport

#702 fix: update stale version
  .ci/Jenkinsfile
  e2e/_suites/fleet/ingest-manager_test.go
Labels: bug

#709 chore: refactor build artifacts methods (#689) backport for 7.x
  cli/docker/docker.go
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/services_test.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-linux-amd64.docker.tar.gz
  e2e/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-ubi8-8.0.0-SNAPSHOT-linux-amd64.docker.tar.gz
  e2e/utils.go
  e2e/utils_test.go
Labels: backport

#710 chore: refactor build artifacts methods (#689) backport for 7.11.x
  cli/docker/docker.go
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/services_test.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-linux-amd64.docker.tar.gz
  e2e/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-ubi8-8.0.0-SNAPSHOT-linux-amd64.docker.tar.gz
  e2e/utils.go
  e2e/utils_test.go
Labels: backport

#713 chore: refactor Fleet upgrade tests (#671) | chore: refactor build artifacts methods (#689) backport for 6.8.x
  .ci/Jenkinsfile
  cli/docker/docker.go
  e2e/Makefile
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/services_test.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-linux-amd64.docker.tar.gz
  e2e/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-ubi8-8.0.0-SNAPSHOT-linux-amd64.docker.tar.gz
  e2e/utils.go
  e2e/utils_test.go
Labels: backport

#711 chore: refactor build artifacts methods (#689) backport for 7.10.x
  cli/docker/docker.go
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/services_test.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-linux-amd64.docker.tar.gz
  e2e/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-ubi8-8.0.0-SNAPSHOT-linux-amd64.docker.tar.gz
  e2e/utils.go
  e2e/utils_test.go
Labels: backport

#714 Metricbeat goal (#705) backport for 7.x
  .ci/Jenkinsfile
  .ci/functionalTests.groovy
  .ci/scripts/functional-test.sh
  .ci/scripts/install-test-dependencies.sh
  .ci/scripts/metricbeat-test.sh
Labels: Team:Automation, automation, backport, ci

#715 Metricbeat goal (#705) backport for 7.11.x
  .ci/Jenkinsfile
  .ci/functionalTests.groovy
  .ci/scripts/functional-test.sh
  .ci/scripts/install-test-dependencies.sh
  .ci/scripts/metricbeat-test.sh
Labels: Team:Automation, automation, backport, ci

#716 Metricbeat goal (#705) backport for 7.10.x
  .ci/Jenkinsfile
  .ci/functionalTests.groovy
  .ci/scripts/functional-test.sh
  .ci/scripts/install-test-dependencies.sh
  .ci/scripts/metricbeat-test.sh
Labels: Team:Automation, automation, backport, ci

#719 fix: use x-pack dir for metricbeat binaries (#718) backport for 7.x
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#721 fix: use x-pack dir for metricbeat binaries (#718) backport for 7.10.x
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#722 fix: use x-pack dir for metricbeat binaries (#718) backport for 6.8.x
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#720 fix: use x-pack dir for metricbeat binaries (#718) backport for 7.11.x
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#717 Metricbeat goal (#705) backport for 6.8.x
  .ci/Jenkinsfile
  .ci/functionalTests.groovy
  .ci/scripts/functional-test.sh
  .ci/scripts/install-test-dependencies.sh
  .ci/scripts/metricbeat-test.sh
Labels: Team:Automation, automation, backport, ci

#724 [JJBB] Increase log rotation
  .ci/Jenkinsfile
  .ci/jobs/defaults.yml
  .ci/jobs/e2e-testing-beats.yml
  .ci/jobs/e2e-testing-mbp.yml
Labels: automation, ci

#729 [JJBB] Increase log rotation (#724) backport for 6.8.x
  .ci/Jenkinsfile
  .ci/jobs/defaults.yml
  .ci/jobs/e2e-testing-beats.yml
  .ci/jobs/e2e-testing-mbp.yml
Labels: automation, backport, ci

#728 [JJBB] Increase log rotation (#724) backport for 7.10.x
  .ci/Jenkinsfile
  .ci/jobs/defaults.yml
  .ci/jobs/e2e-testing-beats.yml
  .ci/jobs/e2e-testing-mbp.yml
Labels: automation, backport, ci

#727 [JJBB] Increase log rotation (#724) backport for 7.11.x
  .ci/Jenkinsfile
  .ci/jobs/defaults.yml
  .ci/jobs/e2e-testing-beats.yml
  .ci/jobs/e2e-testing-mbp.yml
Labels: automation, backport, ci

#726 [JJBB] Increase log rotation (#724) backport for 7.x
  .ci/Jenkinsfile
  .ci/jobs/defaults.yml
  .ci/jobs/e2e-testing-beats.yml
  .ci/jobs/e2e-testing-mbp.yml
Labels: automation, backport, ci

#734 fix: cover fallback cases for shell.GetEnv (#723) backport for 7.10.x
  cli/shell/shell.go
  cli/shell/shell_test.go
Labels: backport

#733 fix: cover fallback cases for shell.GetEnv (#723) backport for 7.11.x
  cli/shell/shell.go
  cli/shell/shell_test.go
Labels: backport

#732 fix: cover fallback cases for shell.GetEnv (#723) backport for 7.x
  cli/shell/shell.go
  cli/shell/shell_test.go
Labels: backport

#735 fix: cover fallback cases for shell.GetEnv (#723) backport for 6.8.x
  cli/shell/shell.go
  cli/shell/shell_test.go
Labels: backport

#736 chore: use alias for stale version (#731) backport for 7.x
  .ci/Jenkinsfile
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#737 chore: use alias for stale version (#731) backport for 7.11.x
  .ci/Jenkinsfile
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#739 chore: use alias for stale version (#731) backport for 6.8.x
  .ci/Jenkinsfile
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#738 chore: use alias for stale version (#731) backport for 7.10.x
  .ci/Jenkinsfile
  .ci/e2eTestingFleetDaily.groovy
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#743 chore: add trace log level on CI (#741) backport for 7.x
  .ci/Jenkinsfile
Labels: backport

#745 chore: add trace log level on CI (#741) backport for 7.10.x
  .ci/Jenkinsfile
Labels: backport

#744 chore: add trace log level on CI (#741) backport for 7.11.x
  .ci/Jenkinsfile
Labels: backport

#746 chore: add trace log level on CI (#741) backport for 6.8.x
  .ci/Jenkinsfile
Labels: backport

#754 fix: use official repository for elasticsearch (#753) backport for 7.11.x
  cli/config/compose/profiles/metricbeat/docker-compose.yml
Labels: backport

#755 fix: use official repository for elasticsearch (#753) backport for 6.8.x
  cli/config/compose/profiles/metricbeat/docker-compose.yml
Labels: backport

#756 fix: support selecting the platform in docker-compose (#751) backport for 7.x
  cli/cmd/sync.go
  cli/cmd/sync_test.go
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/apm-server/docker-compose.yml
  cli/config/compose/services/centos-systemd/docker-compose.yml
  cli/config/compose/services/centos/docker-compose.yml
  cli/config/compose/services/debian-systemd/docker-compose.yml
  cli/config/compose/services/debian/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/compose/services/opbeans-go/docker-compose.yml
  cli/config/compose/services/opbeans-java/docker-compose.yml
  cli/config/compose/services/vsphere/docker-compose.yml
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#758 fix: support selecting the platform in docker-compose (#751) backport for 7.10.x
  cli/cmd/sync.go
  cli/cmd/sync_test.go
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/apm-server/docker-compose.yml
  cli/config/compose/services/centos-systemd/docker-compose.yml
  cli/config/compose/services/centos/docker-compose.yml
  cli/config/compose/services/debian-systemd/docker-compose.yml
  cli/config/compose/services/debian/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/compose/services/opbeans-go/docker-compose.yml
  cli/config/compose/services/opbeans-java/docker-compose.yml
  cli/config/compose/services/vsphere/docker-compose.yml
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#759 fix: support selecting the platform in docker-compose (#751) backport for 6.8.x
  cli/cmd/sync.go
  cli/cmd/sync_test.go
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/apm-server/docker-compose.yml
  cli/config/compose/services/centos-systemd/docker-compose.yml
  cli/config/compose/services/centos/docker-compose.yml
  cli/config/compose/services/debian-systemd/docker-compose.yml
  cli/config/compose/services/debian/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/compose/services/opbeans-go/docker-compose.yml
  cli/config/compose/services/opbeans-java/docker-compose.yml
  cli/config/compose/services/vsphere/docker-compose.yml
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#725 feat: instrument metricbeat test suite
  .ci/Jenkinsfile
  cli/cmd/deploy.go
  cli/cmd/run.go
  cli/config/compose/services/apm-server/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/services/manager.go
  e2e/Makefile
  e2e/README.md
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/elasticsearch.go
  e2e/go.mod
  e2e/go.sum
Labels: automation

#757 fix: support selecting the platform in docker-compose (#751) backport for 7.11.x
  cli/cmd/sync.go
  cli/cmd/sync_test.go
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/apm-server/docker-compose.yml
  cli/config/compose/services/centos-systemd/docker-compose.yml
  cli/config/compose/services/centos/docker-compose.yml
  cli/config/compose/services/debian-systemd/docker-compose.yml
  cli/config/compose/services/debian/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/compose/services/opbeans-go/docker-compose.yml
  cli/config/compose/services/opbeans-java/docker-compose.yml
  cli/config/compose/services/vsphere/docker-compose.yml
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#766 chore: simplify synchronising the integrations (#761) | chore: go version cannot be overriden (#762) backport for 6.8.x
  .ci/scripts/functional-test.sh
  .ci/scripts/install-metricbeat-test-dependencies.sh
  cli/Makefile
  e2e/Makefile
Labels: backport

#769 feat: instrument metricbeat test suite (#725) backport for 7.10.x
  .ci/Jenkinsfile
  cli/cmd/deploy.go
  cli/cmd/run.go
  cli/config/compose/services/apm-server/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/services/manager.go
  e2e/Makefile
  e2e/README.md
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/elasticsearch.go
  e2e/go.mod
  e2e/go.sum
Labels: backport

#763 chore: simplify synchronising the integrations (#761) | chore: go version cannot be overriden (#762) backport for 7.x
  .ci/scripts/functional-test.sh
  .ci/scripts/install-metricbeat-test-dependencies.sh
  cli/Makefile
  e2e/Makefile
Labels: backport

#770 feat: instrument metricbeat test suite (#725) backport for 6.8.x
  .ci/Jenkinsfile
  cli/cmd/deploy.go
  cli/cmd/run.go
  cli/config/compose/services/apm-server/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/services/manager.go
  e2e/Makefile
  e2e/README.md
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/elasticsearch.go
  e2e/go.mod
  e2e/go.sum
Labels: backport

#767 feat: instrument metricbeat test suite (#725) backport for 7.x
  .ci/Jenkinsfile
  cli/cmd/deploy.go
  cli/cmd/run.go
  cli/config/compose/services/apm-server/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/services/manager.go
  e2e/Makefile
  e2e/README.md
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/elasticsearch.go
  e2e/go.mod
  e2e/go.sum
Labels: backport

#768 feat: instrument metricbeat test suite (#725) backport for 7.11.x
  .ci/Jenkinsfile
  cli/cmd/deploy.go
  cli/cmd/run.go
  cli/config/compose/services/apm-server/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/services/manager.go
  e2e/Makefile
  e2e/README.md
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/elasticsearch.go
  e2e/go.mod
  e2e/go.sum
Labels: backport

#764 chore: simplify synchronising the integrations (#761) | chore: go version cannot be overriden (#762) backport for 7.11.x
  .ci/scripts/functional-test.sh
  .ci/scripts/install-metricbeat-test-dependencies.sh
  cli/Makefile
  e2e/Makefile
Labels: backport

#765 chore: simplify synchronising the integrations (#761) | chore: go version cannot be overriden (#762) backport for 7.10.x
  .ci/scripts/functional-test.sh
  .ci/scripts/install-metricbeat-test-dependencies.sh
  cli/Makefile
  e2e/Makefile
Labels: backport

#777 chore: tag docker image after loading it from a file (#772) backport for 7.10.x
  cli/docker/docker.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#778 chore: tag docker image after loading it from a file (#772) backport for 6.8.x
  cli/docker/docker.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#776 chore: tag docker image after loading it from a file (#772) backport for 7.11.x
  cli/docker/docker.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#775 chore: tag docker image after loading it from a file (#772) backport for 7.x
  cli/docker/docker.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#782 e2e fleet: fixed upgrade scenario (#779) backport for 7.10.x
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/installers.go
Labels: backport

#781 e2e fleet: fixed upgrade scenario (#779) backport for 7.11.x
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/installers.go
Labels: backport

#783 e2e fleet: fixed upgrade scenario (#779) backport for 6.8.x
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/installers.go
Labels: backport

#780 e2e fleet: fixed upgrade scenario (#779) backport for 7.x
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/installers.go
Labels: backport

#790 Fleet goal (#784) backport for 7.10.x
  .ci/scripts/fleet-test.sh
Labels: automation, backport

#789 Fleet goal (#784) backport for 7.11.x
  .ci/scripts/fleet-test.sh
Labels: automation, backport

#793 Fleet entrypoint to exclude the nightly tests
  .ci/scripts/fleet-test.sh
Labels: automation, ci

#788 Fleet goal (#784) backport for 7.x
  .ci/scripts/fleet-test.sh
Labels: automation, backport

#791 Fleet goal (#784) backport for 6.8.x
  .ci/scripts/fleet-test.sh
Labels: automation, backport

#792 invalid option in update certificates cmd
  e2e/_suites/fleet/installers.go
Labels: bug

#796 Fleet entrypoint to exclude the nightly tests (#793) backport for 7.10.x
  .ci/scripts/fleet-test.sh
Labels: automation, backport

#795 Fleet entrypoint to exclude the nightly tests (#793) backport for 7.11.x
  .ci/scripts/fleet-test.sh
Labels: automation, backport

#794 Fleet entrypoint to exclude the nightly tests (#793) backport for 7.x
  .ci/scripts/fleet-test.sh
Labels: automation, backport

#797 Fleet entrypoint to exclude the nightly tests (#793) backport for 6.8.x
  .ci/scripts/fleet-test.sh
Labels: automation, backport

#800 invalid option (#792) backport for 7.10.x
  e2e/_suites/fleet/installers.go
Labels: backport

#799 invalid option (#792) backport for 7.11.x
  e2e/_suites/fleet/installers.go
Labels: backport

#805 fix: update flags for the enroll command (#804) backport for 7.x
  e2e/_suites/fleet/services.go
Labels: backport

#808 fix: update flags for the enroll command (#804) backport for 6.8.x
  e2e/_suites/fleet/services.go
Labels: backport

#798 invalid option (#792) backport for 7.x
  e2e/_suites/fleet/installers.go
Labels: backport

#801 invalid option (#792) backport for 6.8.x
  e2e/_suites/fleet/installers.go
Labels: backport

#811 chore: add logs when OS certs are not installed for the upgrade scenario (#809) backport for 7.x
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
Labels: backport

#813 chore: add logs when OS certs are not installed for the upgrade scenario (#809) backport for 7.11.x
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
Labels: backport

#814 chore: add logs when OS certs are not installed for the upgrade scenario (#809) backport for 7.10.x
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
Labels: backport

#812 chore: add logs when OS certs are not installed for the upgrade scenario (#809) backport for 6.8.x
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
Labels: backport

#815 chore: download installers when they are used (#810) backport for 7.x
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest-manager_test.go
Labels: backport

#818 chore: download installers when they are used (#810) backport for 6.8.x
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest-manager_test.go
Labels: backport

#816 chore: download installers when they are used (#810) backport for 7.11.x
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest-manager_test.go
Labels: backport

#817 chore: download installers when they are used (#810) backport for 7.10.x
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest-manager_test.go
Labels: backport
