Repository elastic/e2e-testing, pull requests merged in 2021-09, with the labels that each got.

#1515 [automation] update elastic stack version for testing 7.16.0-8a18fe34
  .stack-version
Labels: automation, dependency

#1521 chore: use our Docker image
  cli/config/kubernetes/overlays/deployment.yaml
Labels: v7.14.0, v7.16.0, v7.15.0

#1525 chore: use staticcheck instead of go-lint
  .ci/scripts/install-dependencies.sh
  .pre-commit-config.yaml
  cli/config/config.go
  internal/deploy/docker.go
  internal/deploy/docker_client.go
  internal/deploy/remote.go
  internal/elasticsearch/assertions.go
  internal/elasticsearch/client.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_docker.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/installer/elasticagent_tar_macos.go
  internal/installer/elasticagent_zip.go
  internal/kibana/agents.go
  internal/kibana/fleet.go
  internal/kibana/url_prefixes.go
  internal/utils/utils.go
Labels: v7.14.0, v7.16.0, v7.15.0

#1503 Normalise APM traces to the same APM service when running in the CI
  .ci/Jenkinsfile
  e2e/commons-test.mk
Labels: area:ci, v7.14.0, v7.16.0, v7.15.0

#1532 chore: revert to golint
  .ci/scripts/install-dependencies.sh
  .pre-commit-config.yaml
Labels: v7.14.0, v7.16.0, v7.15.0

#1519 Move OS specific commands into actions
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/world.go
  go.mod
  go.sum
  internal/action/base.go
  internal/action/process.go
  internal/deploy/base.go
Labels: v7.14.0, v7.16.0, v7.15.0

#1540 [automation] update elastic stack version for testing 8.0.0-467e0885
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1541 [automation] update elastic stack version for testing 7.16.0-a96d8aa5
  .stack-version
Labels: automation, dependency

#1502 feat: support elastic-package provider for Fleet test suite
  .ci/.e2e-tests.yaml
  .ci/Jenkinsfile
  .ci/e2eTestingIntegrationsDaily.groovy
  .ci/jobs/e2e-testing-integrations-daily-mbp.yml
  .ci/scripts/install-metricbeat-test-dependencies.sh
  .go-version
  Makefile
  cli/Makefile
  cli/cmd/sync.go
  cli/cmd/sync_test.go
  cli/config/_testresources/docker-compose-multiple.yml
  cli/config/_testresources/docker-compose-single.yml
  cli/config/config.go
  cli/config/config_test.go
  e2e/README.md
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest_manager_test.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/fleet/world.go
  e2e/_suites/metricbeat/Makefile
  e2e/_suites/metricbeat/README.md
  e2e/_suites/metricbeat/configurations/vsphere.yml
  e2e/_suites/metricbeat/features/integrations.feature
  e2e/_suites/metricbeat/features/metricbeat.feature
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/steps/configurations.go
  go.mod
  go.sum
  internal/action/process.go
  internal/common/defaults.go
  internal/deploy/base.go
  internal/deploy/docker.go
  internal/deploy/docker_client.go
  internal/deploy/elastic_package.go
  internal/deploy/kubernetes.go
  internal/deploy/remote.go
  internal/installer/base.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_docker.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/installer/elasticagent_tar_macos.go
  internal/installer/elasticagent_zip.go
  internal/sanitizer/sanitizer.go
  internal/sanitizer/sanitizer_test.go
  internal/state/state_test.go
  tools/tools.go
Labels: v7.14.0, v7.16.0, v7.15.0

#1550 fix: remove unused code
  cli/config/_testresources/docker-compose-multiple.yml
  cli/config/_testresources/docker-compose-single.yml
  cli/config/config.go
  cli/config/config_test.go
Labels: v7.14.0, v7.15.0

#1545 fix: bump stale agent version to 7.15
  .ci/Jenkinsfile
  internal/common/defaults.go
Labels: skip_backport

#1556 feat: support elastic-package provider for Fleet test suite (#1502) | fix: remove unused code (#1550) backport for 7.x
  .ci/.e2e-tests.yaml
  .ci/Jenkinsfile
  .ci/e2eTestingIntegrationsDaily.groovy
  .ci/jobs/e2e-testing-integrations-daily-mbp.yml
  .ci/scripts/install-metricbeat-test-dependencies.sh
  .go-version
  Makefile
  cli/Makefile
  cli/cmd/_testresources/docker-compose-multiple.yml
  cli/cmd/_testresources/docker-compose-single.yml
  cli/cmd/sync.go
  cli/cmd/sync_test.go
  cli/config/config.go
  e2e/README.md
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest_manager_test.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/fleet/world.go
  e2e/_suites/metricbeat/Makefile
  e2e/_suites/metricbeat/README.md
  e2e/_suites/metricbeat/configurations/vsphere.yml
  e2e/_suites/metricbeat/features/integrations.feature
  e2e/_suites/metricbeat/features/metricbeat.feature
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/steps/configurations.go
  go.mod
  go.sum
  internal/action/process.go
  internal/common/defaults.go
  internal/deploy/base.go
  internal/deploy/docker.go
  internal/deploy/docker_client.go
  internal/deploy/elastic_package.go
  internal/deploy/kubernetes.go
  internal/deploy/remote.go
  internal/installer/base.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_docker.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/installer/elasticagent_tar_macos.go
  internal/installer/elasticagent_zip.go
  internal/sanitizer/sanitizer.go
  internal/sanitizer/sanitizer_test.go
  internal/state/state_test.go
  tools/tools.go
Labels: backport

#1554 feat: support elastic-package provider for Fleet test suite (#1502) | fix: remove unused code (#1550) backport for 7.15.x
  .ci/.e2e-tests.yaml
  .ci/Jenkinsfile
  .ci/e2eTestingIntegrationsDaily.groovy
  .ci/jobs/e2e-testing-integrations-daily-mbp.yml
  .ci/scripts/install-metricbeat-test-dependencies.sh
  .go-version
  Makefile
  cli/Makefile
  cli/cmd/_testresources/docker-compose-multiple.yml
  cli/cmd/_testresources/docker-compose-single.yml
  cli/cmd/sync.go
  cli/cmd/sync_test.go
  cli/config/config.go
  e2e/README.md
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest_manager_test.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/fleet/world.go
  e2e/_suites/metricbeat/Makefile
  e2e/_suites/metricbeat/README.md
  e2e/_suites/metricbeat/configurations/vsphere.yml
  e2e/_suites/metricbeat/features/integrations.feature
  e2e/_suites/metricbeat/features/metricbeat.feature
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/steps/configurations.go
  go.mod
  go.sum
  internal/action/process.go
  internal/common/defaults.go
  internal/deploy/base.go
  internal/deploy/docker.go
  internal/deploy/docker_client.go
  internal/deploy/elastic_package.go
  internal/deploy/kubernetes.go
  internal/deploy/remote.go
  internal/installer/base.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_docker.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/installer/elasticagent_tar_macos.go
  internal/installer/elasticagent_zip.go
  internal/sanitizer/sanitizer.go
  internal/sanitizer/sanitizer_test.go
  internal/state/state_test.go
  tools/tools.go
Labels: backport

#1555 feat: support elastic-package provider for Fleet test suite (#1502) | fix: remove unused code (#1550) backport for 7.14.x
  .ci/.e2e-tests.yaml
  .ci/Jenkinsfile
  .ci/e2eTestingIntegrationsDaily.groovy
  .ci/jobs/e2e-testing-integrations-daily-mbp.yml
  .ci/scripts/install-metricbeat-test-dependencies.sh
  .go-version
  Makefile
  cli/Makefile
  cli/cmd/_testresources/docker-compose-multiple.yml
  cli/cmd/_testresources/docker-compose-single.yml
  cli/cmd/sync.go
  cli/cmd/sync_test.go
  cli/config/config.go
  e2e/README.md
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest_manager_test.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/fleet/world.go
  e2e/_suites/metricbeat/Makefile
  e2e/_suites/metricbeat/README.md
  e2e/_suites/metricbeat/configurations/vsphere.yml
  e2e/_suites/metricbeat/features/integrations.feature
  e2e/_suites/metricbeat/features/metricbeat.feature
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/steps/configurations.go
  go.mod
  go.sum
  internal/action/process.go
  internal/common/defaults.go
  internal/deploy/base.go
  internal/deploy/docker.go
  internal/deploy/docker_client.go
  internal/deploy/elastic_package.go
  internal/deploy/kubernetes.go
  internal/deploy/remote.go
  internal/installer/base.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_docker.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/installer/elasticagent_tar_macos.go
  internal/installer/elasticagent_zip.go
  internal/sanitizer/sanitizer.go
  internal/sanitizer/sanitizer_test.go
  internal/state/state_test.go
  tools/tools.go
Labels: backport

#1558 Update README.md
  README.md
Labels: v7.14.0, v7.16.0, v7.15.0

#1563 [automation] update elastic stack version for testing 7.16.0-468522bc
  .stack-version
Labels: automation, dependency

#1562 [automation] update elastic stack version for testing 8.0.0-c0c740b6
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1568 chore: update paths-labeller
  .github/paths-labeller.yml
Labels: skip_backport

#1566 chore: remove upgrade tests
  .ci/Jenkinsfile
  e2e/README.md
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/fleet.go
  internal/common/defaults.go
  internal/deploy/base.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_docker.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/installer/elasticagent_tar_macos.go
  internal/installer/elasticagent_zip.go
  internal/kibana/agents.go
Labels: skip_backport

#1542 Add context propagation for the tests instrumentation
  .ci/Jenkinsfile
  e2e/_suites/fleet/ingest_manager_test.go
  e2e/_suites/helm/helm_charts_test.go
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
  e2e/commons-test.mk
  e2e/templates/suite_test.go.tmpl
  go.mod
  go.sum
  internal/apm.go
Labels: Team:Automation, area:test, area:ci, v7.14.0, v7.16.0, v7.15.0

#1543 chore: simplify env when consuming Beats CI artifacts
  .ci/Jenkinsfile
  e2e/Makefile
  e2e/README.md
  e2e/_suites/fleet/README.md
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/helm/helm_charts_test.go
  e2e/_suites/kubernetes-autodiscover/README.md
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
  internal/common/defaults.go
  internal/deploy/docker.go
  internal/deploy/docker_test.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_docker.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/installer/elasticagent_tar_macos.go
  internal/installer/elasticagent_zip.go
  internal/utils/utils.go
  internal/utils/utils_test.go
  internal/versions.go
  internal/versions_test.go
Labels: v7.14.0, v7.16.0, v7.15.0

#1578 [automation] update elastic stack version for testing 8.0.0-6b488890
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1579 [automation] update elastic stack version for testing 7.16.0-fbd5fab2
  .stack-version
Labels: automation, dependency

#1580 [automation] update elastic stack version for testing 8.0.0-64718381
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1581 [automation] update elastic stack version for testing 7.16.0-f4fa0a64
  .stack-version
Labels: automation, dependency

#1583 [automation] update elastic stack version for testing 7.16.0-b40a7e80
  .stack-version
Labels: automation, dependency

#1584 [automation] update elastic stack version for testing 8.0.0-da75ec54
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1586 [automation] update elastic stack version for testing 7.16.0-8df9bb12
  .stack-version
Labels: automation, dependency

#1588 fix: use tools as much as possible
  .ci/Jenkinsfile
  .ci/scripts/build-test.sh
  Makefile
  cli/Makefile
  e2e/QUICKSTART.md
  e2e/_suites/fleet/README.md
  e2e/_suites/helm/README.md
  e2e/_suites/kubernetes-autodiscover/README.md
  e2e/commons-test.mk
  go.mod
  go.sum
  tools/tools.go
Labels: v7.14.0, v7.16.0, v7.15.0

#1593 [automation] update elastic stack version for testing 8.0.0-3188f766
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1595 [CI] use obltGitHubComments
  .ci/Jenkinsfile
Labels: automation, v7.14.0, v7.16.0, v7.15.0

#1539 Add process inspection for Windows
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  go.mod
  go.sum
  internal/action/process.go
  internal/deploy/remote.go
  internal/installer/elasticagent_zip.go
  internal/kibana/agents.go
Labels: v7.14.0, v7.16.0, v7.15.0

#1603 Fixes lint error
  internal/installer/elasticagent_zip.go
Labels: v7.14.0, v7.16.0, v7.15.0

#1599 Increase timeout for linux integration
  e2e/_suites/fleet/fleet.go
Labels: v7.14.0, v7.16.0, v7.15.0

#1611 [automation] update elastic stack version for testing 7.16.0-51a7a70c
  .stack-version
Labels: automation, dependency

#1614 [automation] update elastic stack version for testing 8.0.0-61c5a306
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1616 [automation] update elastic stack version for testing 7.16.0-4cbd636a
  .stack-version
Labels: automation, dependency

#1617 [automation] update elastic stack version for testing 8.0.0-9d408327
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1618 [automation] update elastic stack version for testing 7.16.0-25009c74
  .stack-version
Labels: automation, dependency

#1621 chore: report godog tests in junit format on Windows
  .ci/Jenkinsfile
Labels: v7.14.0, v7.16.0, v7.15.0

#1623 [automation] update elastic stack version for testing 7.16.0-f67263fd
  .stack-version
Labels: automation, dependency
