Repository elastic/e2e-testing, pull requests merged in 2021-01, with the labels that each got.

#553 chore: simplify jUnit format generation with gotestsum (#549) | fix: use golangci-lint in favour of go-critic (#550) backport for 7.x
  .ci/scripts/build-test.sh
  .ci/scripts/install-dependencies.sh
  .pre-commit-config.yaml
  cli/Makefile
  cli/internal/state.go
  e2e/runner_test.go
  e2e/utils.go
Labels: backport

#554 chore: simplify jUnit format generation with gotestsum (#549) | fix: use golangci-lint in favour of go-critic (#550) backport for 7.10.x
  .ci/scripts/build-test.sh
  .ci/scripts/install-dependencies.sh
  .pre-commit-config.yaml
  cli/Makefile
  cli/internal/state.go
  e2e/runner_test.go
  e2e/utils.go
Labels: backport

#556 chore: update Fleet properties in Kibana (#555) backport for 7.x
  e2e/_suites/fleet/configurations/kibana.config.yml
Labels: backport

#562 fix: make docker namespace configurable (#560) backport for 7.10.x
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#561 fix: make docker namespace configurable (#560) backport for 7.x
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#565 fix: set image version before switching to the configuration file
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: bug

#568 chore: rename ELASTIC_AGENT_USE_CI_SNAPSHOTS (#566) | fix: set image version before switching to the configuration file (#565) backport for 7.x
  .ci/Jenkinsfile
  e2e/_suites/fleet/README.md
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/README.md
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/utils.go
Labels: backport

#569 chore: rename ELASTIC_AGENT_USE_CI_SNAPSHOTS (#566) | fix: set image version before switching to the configuration file (#565) backport for 7.10.x
  .ci/Jenkinsfile
  e2e/_suites/fleet/README.md
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/README.md
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/utils.go
Labels: backport

#571 fix: monitor PRs and tags too
  .ci/jobs/e2e-testing-mbp.yml
Labels: bug

#576 fix: use proper server.host in Kibana
  cli/config/compose/profiles/fleet/docker-compose.yml
  e2e/_suites/fleet/configurations/kibana.config.yml
Labels: skip_backport

#507 feat: support more integrations
  .ci/.e2e-tests.yaml
  cli/cmd/sync.go
  cli/config/config.go
  cli/services/sanitizer.go
  cli/services/sanitizer_test.go
  e2e/_suites/metricbeat/configurations/apache.yml
  e2e/_suites/metricbeat/configurations/mysql.yml
  e2e/_suites/metricbeat/configurations/redis.yml
  e2e/_suites/metricbeat/configurations/vsphere.yml
  e2e/_suites/metricbeat/features/integrations.feature
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/assertions.go
Labels: metricbeat

#558 [7.x] Backport #537
  .ci/Jenkinsfile
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/fleet/services.go
  e2e/go.mod
Labels: backport

#587 [JJBB] Increase shallow cloning
  .ci/jobs/e2e-testing-mbp.yml
Labels: automation

#592 chore: store container logs in Jenkins (#577) backport for 6.8.x
  .ci/Jenkinsfile
  cli/shell/shell.go
  cli/shell/shell_test.go
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/fleet/services.go
  e2e/_suites/helm/helm_charts_test.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/utils.go
Labels: backport

#591 chore: store container logs in Jenkins (#577) backport for 7.11.x
  .ci/Jenkinsfile
  cli/shell/shell.go
  cli/shell/shell_test.go
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/fleet/services.go
  e2e/_suites/helm/helm_charts_test.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/utils.go
Labels: backport

#597 chore: bump godog to v0.11.0 (#590) backport for 6.8.x
  .ci/scripts/functional-test.sh
  e2e/Makefile
  e2e/NOTICE.txt
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/helm/helm_charts_test.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/go.mod
  e2e/go.sum
Labels: backport

#598 fix: add artifact name to the bucket URI
  e2e/_suites/fleet/services.go
Labels: bug

#599 fix: add artifact name to the bucket URI (#598) backport for 7.x
  e2e/_suites/fleet/services.go
Labels: backport

#600 fix: add artifact name to the bucket URI (#598) backport for 7.11.x
  e2e/_suites/fleet/services.go
Labels: backport

#601 fix: add artifact name to the bucket URI (#598) backport for 7.10.x
  e2e/_suites/fleet/services.go
Labels: backport

#603 fix: properly calculate GCP storage bucket URIs for PRs and snapshots (#602) backport for 7.x
  .ci/Jenkinsfile
  .ci/scripts/build-test.sh
  e2e/Makefile
  e2e/_suites/fleet/services.go
  e2e/_testresources/gcp/nextPageParam.json
  e2e/_testresources/gcp/pull-requests.json
  e2e/_testresources/gcp/snapshots.json
  e2e/go.mod
  e2e/utils.go
  e2e/utils_test.go
Labels: backport

#604 fix: properly calculate GCP storage bucket URIs for PRs and snapshots (#602) backport for 7.11.x
  .ci/Jenkinsfile
  .ci/scripts/build-test.sh
  e2e/Makefile
  e2e/_suites/fleet/services.go
  e2e/_testresources/gcp/nextPageParam.json
  e2e/_testresources/gcp/pull-requests.json
  e2e/_testresources/gcp/snapshots.json
  e2e/go.mod
  e2e/utils.go
  e2e/utils_test.go
Labels: backport

#606 fix: properly calculate GCP storage bucket URIs for PRs and snapshots (#602) backport for 6.8.x
  .ci/Jenkinsfile
  .ci/scripts/build-test.sh
  e2e/Makefile
  e2e/_suites/fleet/services.go
  e2e/_testresources/gcp/nextPageParam.json
  e2e/_testresources/gcp/pull-requests.json
  e2e/_testresources/gcp/snapshots.json
  e2e/go.mod
  e2e/utils.go
  e2e/utils_test.go
Labels: backport

#605 fix: properly calculate GCP storage bucket URIs for PRs and snapshots (#602) backport for 7.10.x
  .ci/Jenkinsfile
  .ci/scripts/build-test.sh
  e2e/Makefile
  e2e/_suites/fleet/services.go
  e2e/_testresources/gcp/nextPageParam.json
  e2e/_testresources/gcp/pull-requests.json
  e2e/_testresources/gcp/snapshots.json
  e2e/go.mod
  e2e/utils.go
  e2e/utils_test.go
Labels: backport

#608 docs: document how to trigger the tests for Beats PR
  e2e/README.md
Labels: documentation

#609 docs: document how to trigger the tests for Beats PR (#608) backport for 7.x
  e2e/README.md
Labels: backport

#610 docs: document how to trigger the tests for Beats PR (#608) backport for 7.11.x
  e2e/README.md
Labels: backport

#611 docs: document how to trigger the tests for Beats PR (#608) backport for 7.10.x
  e2e/README.md
Labels: backport

#612 docs: document how to trigger the tests for Beats PR (#608) backport for 6.8.x
  e2e/README.md
Labels: backport

#614 chore: fix issues with golangci-lint (#613) backport for 7.x
  .pre-commit-config.yaml
  .vscode/launch.json
  cli/Building.md
  cli/LICENSE.txt
  doc.go
  e2e/LICENSE.txt
  e2e/_suites/metricbeat/configurations/vsphere.yml
  go.mod
  notice/NOTICE.txt.tmpl
  notice/rules.json
Labels: backport

#616 chore: fix issues with golangci-lint (#613) backport for 7.10.x
  .pre-commit-config.yaml
  .vscode/launch.json
  cli/Building.md
  cli/LICENSE.txt
  doc.go
  e2e/LICENSE.txt
  e2e/_suites/metricbeat/configurations/vsphere.yml
  go.mod
  notice/NOTICE.txt.tmpl
  notice/rules.json
Labels: backport

#617 chore: fix issues with golangci-lint (#613) backport for 6.8.x
  .pre-commit-config.yaml
  .vscode/launch.json
  cli/Building.md
  cli/LICENSE.txt
  doc.go
  e2e/LICENSE.txt
  e2e/_suites/metricbeat/configurations/vsphere.yml
  go.mod
  notice/NOTICE.txt.tmpl
  notice/rules.json
Labels: backport

#615 chore: fix issues with golangci-lint (#613) backport for 7.11.x
  .pre-commit-config.yaml
  .vscode/launch.json
  cli/Building.md
  cli/LICENSE.txt
  doc.go
  e2e/LICENSE.txt
  e2e/_suites/metricbeat/configurations/vsphere.yml
  go.mod
  notice/NOTICE.txt.tmpl
  notice/rules.json
Labels: backport

#618 chore: increase timeout for Ceph
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/elasticsearch.go
  e2e/utils.go
Labels: Flaky Test, metricbeat

#619 chore: increase timeout for Ceph (#618) backport for 7.x
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/elasticsearch.go
  e2e/utils.go
Labels: backport

#620 chore: increase timeout for Ceph (#618) backport for 7.11.x
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/elasticsearch.go
  e2e/utils.go
Labels: backport

#621 chore: increase timeout for Ceph (#618) backport for 7.10.x
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/elasticsearch.go
  e2e/utils.go
Labels: backport

#622 chore: increase timeout for Ceph (#618) backport for 6.8.x
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/elasticsearch.go
  e2e/utils.go
Labels: backport

#623 fix: typo in precommit docs
  README.md
  e2e/README.md
Labels: P3, bug, documentation

#624 chore: increase timeout in CI
  .ci/Jenkinsfile
Labels: automation

#632 fix: let godog handle the creation of the junit test file (#629) backport for 7.11.x
  .ci/scripts/functional-test.sh
Labels: backport

#633 fix: let godog handle the creation of the junit test file (#629) backport for 7.10.x
  .ci/scripts/functional-test.sh
Labels: backport

#634 fix: let godog handle the creation of the junit test file (#629) backport for 6.8.x
  .ci/scripts/functional-test.sh
Labels: backport

#630 fix: do not override compose configurations when syncing from beats
  cli/cmd/_testresources/docker-compose-multiple.yml
  cli/cmd/_testresources/docker-compose-single.yml
  cli/cmd/sync.go
  cli/cmd/sync_test.go
Labels: bug

#631 fix: let godog handle the creation of the junit test file (#629) backport for 7.x
  .ci/scripts/functional-test.sh
Labels: backport

#639 chore: skip ceph tests (#635) backport for 6.8.x
  e2e/_suites/metricbeat/features/integrations.feature
Labels: backport

#638 chore: skip ceph tests (#635) backport for 7.10.x
  e2e/_suites/metricbeat/features/integrations.feature
Labels: backport

#637 chore: skip ceph tests (#635) backport for 7.11.x
  e2e/_suites/metricbeat/features/integrations.feature
Labels: backport

#636 chore: skip ceph tests (#635) backport for 7.x
  e2e/_suites/metricbeat/features/integrations.feature
Labels: backport

#647 fix: do not override compose configurations when syncing from beats (#630) backport for 7.11.x
  cli/cmd/_testresources/docker-compose-multiple.yml
  cli/cmd/_testresources/docker-compose-single.yml
  cli/cmd/sync.go
  cli/cmd/sync_test.go
Labels: backport

#648 fix: do not override compose configurations when syncing from beats (#630) backport for 7.10.x
  cli/cmd/_testresources/docker-compose-multiple.yml
  cli/cmd/_testresources/docker-compose-single.yml
  cli/cmd/sync.go
  cli/cmd/sync_test.go
Labels: backport

#649 fix: do not override compose configurations when syncing from beats (#630) backport for 6.8.x
  cli/cmd/_testresources/docker-compose-multiple.yml
  cli/cmd/_testresources/docker-compose-single.yml
  cli/cmd/sync.go
  cli/cmd/sync_test.go
Labels: backport

#646 fix: do not override compose configurations when syncing from beats (#630) backport for 7.x
  cli/cmd/_testresources/docker-compose-multiple.yml
  cli/cmd/_testresources/docker-compose-single.yml
  cli/cmd/sync.go
  cli/cmd/sync_test.go
Labels: backport

#661 chore: decouple installer packages (#651) backport for 7.11.x
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
Labels: backport

#662 chore: decouple installer packages (#651) backport for 7.10.x
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
Labels: backport

#660 chore: decouple installer packages (#651) backport for 7.x
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
Labels: backport

#663 chore: decouple installer packages (#651) backport for 6.8.x
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
Labels: backport

#667 chore: use a more structured YAML format (#654) backport for 6.8.x
  .ci/.e2e-tests.yaml
  .ci/Jenkinsfile
Labels: backport

#665 chore: use a more structured YAML format (#654) backport for 7.11.x
  .ci/.e2e-tests.yaml
  .ci/Jenkinsfile
Labels: backport

#666 chore: use a more structured YAML format (#654) backport for 7.10.x
  .ci/.e2e-tests.yaml
  .ci/Jenkinsfile
Labels: backport

#664 chore: use a more structured YAML format (#654) backport for 7.x
  .ci/.e2e-tests.yaml
  .ci/Jenkinsfile
Labels: backport

#675 fix: notify build result only once (#673) backport for 7.11.x
  .ci/Jenkinsfile
Labels: backport

#676 fix: notify build result only once (#673) backport for 7.10.x
  .ci/Jenkinsfile
Labels: backport

#677 fix: notify build result only once (#673) backport for 6.8.x
  .ci/Jenkinsfile
Labels: backport

#674 fix: notify build result only once (#673) backport for 7.x
  .ci/Jenkinsfile
Labels: backport
