Repository elastic/e2e-testing, pull requests merged in 2021-04, with the labels that each got.

#985 cli: support passing in environment options and better service def
  cli/README.md
  cli/cmd/run.go
Labels: enhancement

#993 Uniquify the stand-alone step for checking agent status
  e2e/_suites/fleet/features/stand_alone_agent.feature
  e2e/_suites/fleet/stand-alone.go
Labels: v7.11.0, v7.12.0, v7.13.0

#1011 chore: simplify PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip_backport

#1010 fix: use same JJB than in custom kibana
  .ci/jobs/kibana-e2e-tests.yml
Labels: ci

#1016 fix: delay checking stale agent version until it's used
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest_manager_test.go
  e2e/_suites/helm/helm_charts_test.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/utils.go
Labels: v7.11.0, v7.12.0, v7.13.0

#1017 remove uninstall step
  e2e/_suites/fleet/features/fleet_mode_agent.feature
Labels: v7.11.0, v7.12.0, v7.13.0

#1029 fix(jjb): use a branch that exists
  .ci/jobs/kibana-e2e-tests.yml
Labels: ci, skip_backport

#1030 fix: use an agent when building kibana
  .ci/e2eKibana.groovy
Labels: bug

#1038 fix: add NodeJS to PATH (#1035) | fix: apply X version for non-master branches (#1037) backport for 7.x
  .ci/e2eKibana.groovy
Labels: backport

#1039 fix: add NodeJS to PATH (#1035) | fix: apply X version for non-master branches (#1037) backport for 7.12.x
  .ci/e2eKibana.groovy
Labels: backport

#1040 fix: add NodeJS to PATH (#1035) | fix: apply X version for non-master branches (#1037) backport for 7.11.x
  .ci/e2eKibana.groovy
Labels: backport

#900 feat: add first scenario for Fleet Server
  .ci/.e2e-tests.yaml
  cli/config/compose/profiles/fleet/configurations/kibana.config.yml
  cli/docker/docker.go
  e2e/_suites/fleet/features/fleet_server.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/fleet_server.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
Labels: Team:Agent

#1057 fix: wrong interpolation (#1042) | chore: add debug traces for the webhook payload (#1043) | chore: add debug info for the payload (#1044) | fix: typo in parameters (#1045) | fix: incorrect variable name (#1046) | fix: do not use GT_REPO va
  .ci/e2eKibana.groovy
Labels: backport

#1058 fix: wrong interpolation (#1042) | chore: add debug traces for the webhook payload (#1043) | chore: add debug info for the payload (#1044) | fix: typo in parameters (#1045) | fix: incorrect variable name (#1046) | fix: do not use GT_REPO va
  .ci/e2eKibana.groovy
Labels: backport

#1059 fix: wrong interpolation (#1042) | chore: add debug traces for the webhook payload (#1043) | chore: add debug info for the payload (#1044) | fix: typo in parameters (#1045) | fix: incorrect variable name (#1046) | fix: do not use GT_REPO va
  .ci/e2eKibana.groovy
Labels: backport

#1067 fix: run unit tests after refactor
  .ci/scripts/build-test.sh
  Makefile
  cli/internal/git.go
  cli/internal/git_test.go
  cli/internal/io.go
  cli/internal/io_test.go
  cli/internal/state.go
  cli/internal/state_test.go
  commons.mk
  e2e/Makefile
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-amd64.deb
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-linux-amd64.docker.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-linux-amd64.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-x86_64.rpm
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-ubi8-8.0.0-SNAPSHOT-linux-amd64.docker.tar.gz
  internal/_testresources/gcp/commits.json
  internal/_testresources/gcp/nextPageParam.json
  internal/_testresources/gcp/snapshots.json
  internal/installer/base_test.go
  internal/utils/utils_test.go
Labels: v7.13.0

#1092 Move kubernetes/kubectl/kind code to internal project layout
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
  internal/kubernetes/kubernetes.go
Labels: enhancement

#1097 fix: branch_specifier is needed
  .ci/build-docker-images.groovy
  .ci/jobs/build-docker-images.yml
Labels: skip_backport

#1100 feat: add scheduled pipeline for k8s autodiscovery test suite
  .ci/e2eTestingK8SAutodiscoveryDaily.groovy
  .ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml
  README.md
Labels: skip_backport
