Repository elastic/e2e-testing, pull requests merged in 2021-05, with the labels that each got.

#1123 Pull fresh docker images before suite
  e2e/README.md
  e2e/_suites/fleet/ingest_manager_test.go
  internal/docker/docker.go
Labels: enhancement

#1149 fix: rename downloaded file using artifact name
  internal/utils/utils.go
Labels: v7.13.0, v7.14.0

#1158 chore(mergify): delete upstream branches on merge
  .mergify.yml
Labels: skip_backport

#1164 feat: make a stronger verification of fleet-server being bootstrapped
  e2e/_suites/fleet/features/stand_alone_agent.feature
Labels: v7.14.0

#1171 fix: resolve issues in k8s-autodiscover test suite
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
  internal/deploy/docker_client.go
Labels: v7.13.0, v7.14.0

#1180 chore: remove upgrade agent for 7.13
  .ci/Jenkinsfile
  e2e/README.md
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/fleet.go
  internal/installer/base.go
  internal/installer/deb.go
  internal/installer/docker.go
  internal/installer/elasticagent.go
  internal/installer/rpm.go
  internal/installer/tar.go
Labels: skip_backport

#1181 docs: document integrations in the proper README file
  e2e/_suites/fleet/README.md
  e2e/_suites/metricbeat/README.md
Labels: area:documentation, bug, v7.13.0, v7.14.0

#1186 fix: run linux integration on CI
  .ci/.e2e-tests.yaml
Labels: v7.12.0, v7.13.0, v7.14.0

#1190 fix: make sure debian boxes have the right tools for testing
  .ci/docker/debian-systemd/Dockerfile
Labels: Team:Automation, bug, skip_backport

#1163 Update installer code to support deployer abstraction
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/fleet/world.go
  internal/deploy/base.go
  internal/deploy/docker.go
  internal/deploy/docker_client.go
  internal/deploy/docker_client_test.go
  internal/deploy/kubernetes.go
  internal/installer/base.go
  internal/installer/deb.go
  internal/installer/elasticagent.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/installer/rpm.go
  internal/installer/tar.go
  internal/kibana/fleet.go
Labels: v7.13.0, v7.14.0

#1193 feat: support for running feature files
  .ci/scripts/functional-test.sh
  .github/PULL_REQUEST_TEMPLATE.md
  e2e/Makefile
  e2e/README.md
  e2e/_suites/fleet/Makefile
  e2e/_suites/helm/Makefile
  e2e/_suites/kubernetes-autodiscover/Makefile
  e2e/_suites/metricbeat/Makefile
  e2e/commons-test.mk
Labels: v7.13.0, v7.14.0

#1208 Feat installer rework 2
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest_manager_test.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/fleet/world.go
  internal/common/defaults.go
  internal/deploy/base.go
  internal/deploy/docker.go
  internal/deploy/docker_client.go
  internal/deploy/docker_client_test.go
  internal/deploy/kubernetes.go
  internal/installer/base.go
  internal/installer/deb.go
  internal/installer/docker.go
  internal/installer/elasticagent.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_docker.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/installer/rpm.go
  internal/installer/tar.go
  internal/kibana/fleet.go
Labels: v7.13.0, v7.14.0
