Repository elastic/e2e-testing, pull requests merged in 2021-12, with the labels that each got.

#1857 [automation] update elastic stack version for testing 8.0.0-df873dde
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1860 [automation] update elastic stack version for testing 8.1.0-274c36a2
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1861 [mergify] use merge queue
  .mergify.yml
Labels: automation, backport-skip

#1858 [automation] update elastic stack version for testing 7.15.3-ac0a2edb
  .stack-version
Labels: automation, dependency, backport-skip

#1859 [automation] update elastic stack version for testing 7.16.0-046aeba5
  .stack-version
Labels: automation, dependency, backport-skip

#1862 Fixes #1847
  internal/kibana/integrations.go
Labels: backport-skip

#1852 [mergify] close stalled PRs with the bump automation
  .mergify.yml
Labels: backport-skip

#1866 [automation] update elastic stack version for testing 7.15.3-1d3806ef
  .stack-version
Labels: automation, dependency, backport-skip

#1864 [automation] update elastic stack version for testing 8.0.0-aab6301c
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1863 [automation] update elastic stack version for testing 7.16.0-80ab1dd0
  .stack-version
Labels: automation, dependency, backport-skip

#1871 [automation] update elastic stack version for testing 7.16.0-f17274e7
  .stack-version
Labels: automation, dependency, backport-skip

#1870 [automation] update elastic stack version for testing 7.15.3-2191b0f7
  .stack-version
Labels: automation, dependency, backport-skip

#1868 [automation] update elastic stack version for testing 8.0.0-eda77a0f
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1873 [automation] update elastic stack version for testing 7.16.0-ef210289
  .stack-version
Labels: automation, dependency, backport-skip

#1876 [automation] update elastic stack version for testing 7.15.3-70c2e21f
  .stack-version
Labels: automation, dependency, backport-skip

#1880 [automation] update elastic stack version for testing 7.16.0-f2941f42
  .stack-version
Labels: automation, dependency, backport-skip

#1878 [automation] update elastic stack version for testing 7.15.3-9e171938
  .stack-version
Labels: automation, dependency, backport-skip

#1884 [automation] update elastic stack version for testing 7.16.0-eaf40d57
  .stack-version
Labels: automation, dependency, backport-skip

#1882 [automation] update elastic stack version for testing 7.15.3-984b6e42
  .stack-version
Labels: automation, dependency, backport-skip

#1886 [automation] update elastic stack version for testing 7.16.1-53c0de77
  .stack-version
Labels: automation, dependency, backport-skip

#1887 [automation] update elastic stack version for testing 7.15.3-67d7b6ce
  .stack-version
Labels: automation, dependency, backport-skip

#1891 [automation] update elastic stack version for testing 7.16.1-1d21f78b
  .stack-version
Labels: automation, dependency, backport-skip

#1889 [automation] update elastic stack version for testing 8.1.0-3cacb07d
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1892 [automation] update elastic stack version for testing 7.16.1-2ceb4af4
  .stack-version
Labels: automation, dependency, backport-skip

#1894 [automation] update elastic stack version for testing 8.1.0-b6e7e1f3
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1877 [Fleet] Fix tests after changes in API
  e2e/_suites/fleet/README.md
  internal/kibana/agents.go
  internal/kibana/integrations.go
  internal/kibana/policies.go
  internal/kibana/server.go
Labels: v8.0.0, v8.1.0, backport-v8.0.0

#1897 [automation] update elastic stack version for testing 7.16.2-926bc45c
  .stack-version
Labels: automation, dependency, backport-skip

#1896 chore: add package name to error logs and spans
  internal/kibana/integrations.go
Labels: backport-v7.16.0, backport-v8.0.0, backport-v7.15.0, backport-v8.1.0

#1901 chore: do not exit with log.Fatal while reading JSON file
  e2e/_suites/fleet/fleet.go
Labels: backport-v7.16.0, backport-v8.0.0, backport-v7.15.0

#1893 [automation] update elastic stack version for testing 8.0.0-3c6e08ba
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1910 [automation] update elastic stack version for testing 7.16.2-5ee0e439
  .stack-version
Labels: automation, dependency, backport-skip

#1909 [automation] update elastic stack version for testing 8.1.0-f02e597e
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1908 [automation] update elastic stack version for testing 8.0.0-6b5f794c
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1911 [automation] update elastic stack version for testing 7.16.2-e7a873d4
  .stack-version
Labels: automation, dependency, backport-skip

#1914 fix: add resiliency when an integration cannot be added to a policy
  e2e/_suites/fleet/fleet.go
  internal/kibana/integrations.go
Labels: bug, Team:Automation, Team:Integrations, backport-v7.16.0, backport-v8.0.0, backport-v7.15.0

#1922 [automation] update elastic stack version for testing 7.16.2-682993ae
  .stack-version
Labels: automation, dependency, backport-skip

#1921 [automation] update elastic stack version for testing 8.1.0-60bffc32
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1924 chore: properly evaluate how tests are skipped on CI when checking modified files
  .ci/Jenkinsfile
Labels: backport-v7.16.0, backport-v8.0.0, backport-v7.15.0

#1929 [automation] update elastic stack version for testing 8.1.0-befff95a
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1930 [automation] update elastic stack version for testing 8.0.0-002bf944
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1928 Update main branch
  .ci/Jenkinsfile
  .ci/build-docker-images.groovy
  .ci/e2eFleetServer.groovy
  .ci/e2eKibana.groovy
  .ci/jobs/build-docker-images.yml
  .ci/jobs/e2e-testing-fleet-daily-mbp.yml
  .ci/jobs/e2e-testing-helm-daily-mbp.yml
  .ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml
  .ci/jobs/e2e-testing-mbp.yml
  .ci/jobs/fleet-server-e2e-tests.yml
  .ci/jobs/kibana-e2e-tests.yml
  .mergify.yml
  README.md
  cli/README.md
  e2e/README.md
Labels: backport-skip, backport-v7.16.0, backport-v8.0.0, backport-v7.15.0, backport-v7.17.0

#1917 ci: use withAPMEnv
  .ci/Jenkinsfile
Labels: backport-v7.16.0, backport-v8.0.0

#1936 [automation] update elastic stack version for testing 8.0.0-7b79b556
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1938 chore: retire 7.15 adding 7.17
  .backportrc.json
  .ci/jobs/e2e-testing-fleet-daily-mbp.yml
  .ci/jobs/e2e-testing-helm-daily-mbp.yml
  .ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml
  .ci/jobs/e2e-testing-mbp.yml
  .mergify.yml
Labels: skip_backport, Team:Automation, area:ci, backport-skip

#1937 chore: bump versions for 7.17
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  e2e/README.md
  e2e/_suites/fleet/README.md
  internal/common/defaults.go
Labels: skip_backport, Team:Automation, area:test, backport-skip

#1947 [automation] update elastic stack version for testing 7.17.0-e76712ab
  .stack-version
Labels: automation, dependency, backport-skip

#1946 [automation] update elastic stack version for testing 8.1.0-76902d39
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1944 [automation] update elastic stack version for testing 8.0.0-52f8db06
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1948 [automation] update elastic stack version for testing 8.1.0-dbc834fd
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1949 [automation] update elastic stack version for testing 7.17.0-6e4bbd35
  .stack-version
Labels: automation, dependency, backport-skip

#1953 [automation] update elastic stack version for testing 7.17.0-09b71949
  .stack-version
Labels: automation, dependency, backport-skip

#1957 [automation] update elastic stack version for testing 7.17.0-c02e8773
  .stack-version
Labels: automation, dependency, backport-skip

#1960 [automation] update elastic stack version for testing 7.17.0-a34e30fc
  .stack-version
Labels: automation, dependency, backport-skip

#1963 [automation] update elastic stack version for testing 7.17.0-53d9a9d2
  .stack-version
Labels: automation, dependency, backport-skip
