Repository elastic/e2e-testing, pull requests merged in 2021-08, with the labels that each got.

#1425 docs: revamp docs
  README.md
  cli/Makefile
  cli/README.md
  e2e/Makefile
  e2e/QUICKSTART.md
  e2e/README.md
  e2e/TROUBLESHOOTING.md
  e2e/_suites/fleet/README.md
  e2e/_suites/helm/README.md
  e2e/_suites/kubernetes-autodiscover/README.md
  e2e/_suites/metricbeat/README.md
  e2e/_suites/metricbeat/metricbeat-poc.md
  e2e/commons-test.mk
  e2e/debug.png
  e2e/generate-suite.sh
  e2e/templates/profile.yml.tmpl
  e2e/templates/suite.feature.tmpl
  e2e/templates/suite_test.go.tmpl
  internal/utils/utils.go
Labels: v7.13.0, v7.14.0, v7.15.0

#1440 Fix documentation link
  e2e/README.md
Labels: v7.13.0, v7.14.0, v7.15.0

#1452 chore: skip endpoint scenarios from CI
  .ci/.e2e-tests.yaml
  e2e/_suites/fleet/ingest_manager_test.go
Labels: v7.13.0, v7.14.0, v7.15.0

#1459 chore: calculate version in context
  e2e/_suites/metricbeat/metricbeat_test.go
  internal/installer/elasticagent_tar.go
  internal/installer/elasticagent_tar_macos.go
  internal/installer/elasticagent_zip.go
  internal/utils/utils.go
  internal/utils/utils_test.go
  internal/versions.go
  internal/versions_test.go
Labels: v7.13.0, v7.14.0, v7.15.0

#1457 [automation] update elastic stack version for testing 8.0.0-2e89a578
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1450 New code for Stand-Alone Agent with System Integration
  e2e/_suites/fleet/features/stand_alone_agent.feature
Labels: v7.13.0, area:test, v7.14.0, v7.15.0

#1466 [automation] update elastic stack version for testing 8.0.0-7e122dd9
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1470 fix: use version without commit when upgrading the agent
  e2e/_suites/fleet/fleet.go
Labels: v7.14.0, v7.15.0

#1467 [automation] update elastic stack version for testing 7.15.0-4b8a78a4
  .stack-version
Labels: automation, dependency

#1479 chore: calculate version in context (#1459) backport for 7.13.x
  e2e/_suites/metricbeat/metricbeat_test.go
  internal/installer/elasticagent_tar.go
  internal/installer/elasticagent_tar_macos.go
  internal/installer/elasticagent_zip.go
  internal/utils/utils.go
  internal/utils/utils_test.go
  internal/versions.go
  internal/versions_test.go
Labels: backport

#1480 chore: grab stack logs
  .ci/Jenkinsfile
Labels: v7.13.0, v7.14.0, v7.15.0

#1487 fix: proper usage of filebeat step
  .ci/Jenkinsfile
Labels: v7.13.0, v7.14.0, v7.15.0

#1485 [automation] update elastic stack version for testing 8.0.0-8ac8c039
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1493 chore: retire 7.13.x branch in favour of 7.15.x
  .backportrc.json
  .ci/jobs/e2e-testing-fleet-daily-mbp.yml
  .ci/jobs/e2e-testing-helm-daily-mbp.yml
  .ci/jobs/e2e-testing-integrations-daily-mbp.yml
  .ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml
  .ci/jobs/e2e-testing-mbp.yml
  .mergify.yml
Labels: skip_backport

#1495 [automation] update elastic stack version for testing 8.0.0-56a61c29
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1472 chore: increase builds to keep
  .ci/jobs/e2e-testing-mbp.yml
Labels: skip_backport

#1494 [automation] update elastic stack version for testing 7.16.0-2d73c7e8
  .stack-version
Labels: automation, dependency

#1496 [automation] update elastic stack version for testing 7.16.0-c3b80e7b
  .stack-version
Labels: automation, dependency

#1500 [automation] update elastic stack version for testing 8.0.0-126d5980
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1510 [automation] update elastic stack version for testing 8.0.0-1efff7fc
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1509 [automation] update elastic stack version for testing 7.16.0-d98a671f
  .stack-version
Labels: automation, dependency

#1514 [automation] update elastic stack version for testing 8.0.0-78724554
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency
