Repository elastic/e2e-testing, pull requests merged in 2021-06, with the labels that each got.

#707 feat: add support for running the tests in ARM
  .ci/.e2e-tests.yaml
  .ci/Jenkinsfile
  .ci/packer_cache.sh
  .ci/scripts/clean-docker.sh
  .ci/scripts/functional-test.sh
  .ci/scripts/install-helm-test-dependencies.sh
  cli/config/compose/profiles/fleet/configurations/kibana.config.yml
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/centos/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/debian/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/fleet-server-centos/docker-compose.yml
  cli/config/compose/services/fleet-server-debian/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  e2e/_suites/fleet/features/agent_endpoint_integration.feature
  e2e/_suites/fleet/ingest_manager_test.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/commons-test.mk
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-aarch64.rpm
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-arm64.deb
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-linux-arm64.docker.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-linux-arm64.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-8.0.0-SNAPSHOT-linux-x86_64.tar.gz
  internal/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-ubi8-8.0.0-SNAPSHOT-linux-arm64.docker.tar.gz
  internal/deploy/docker.go
  internal/deploy/docker_client.go
  internal/installer/base_test.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_docker.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/utils/utils.go
  internal/utils/utils_test.go
Labels: Team:Obs-DC, area:test, priority:high, size:XL, triaged

#1216 chore: support running a build as the master branch
  .ci/Jenkinsfile
Labels: v7.13.0, v7.14.0

#1217 chore: handle APM errors properly
  e2e/_suites/helm/helm_charts_test.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: v7.13.0, v7.14.0

#1218 chore: initialise shared variables only once
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest_manager_test.go
  e2e/_suites/helm/helm_charts_test.go
  e2e/_suites/metricbeat/metricbeat_test.go
  internal/common/defaults.go
  internal/elasticsearch/client.go
Labels: v7.13.0, v7.14.0

#1235 fix: do not use variable out of its scope (#1231) backport for 7.x
  .ci/Jenkinsfile
Labels: backport

#1236 fix: do not use variable out of its scope (#1231) backport for 7.13.x
  .ci/Jenkinsfile
Labels: backport

#1238 feat: add APM traces for Fleet test suite (#1234) backport for 7.x
  .ci/Jenkinsfile
  cli/config/compose/profiles/helm/docker-compose.yml
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest_manager_test.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/fleet/world.go
  e2e/_suites/helm/helm_charts_test.go
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/commons-test.mk
  e2e/steps/befores.go
  internal/common/defaults.go
  internal/deploy/base.go
  internal/deploy/compose.go
  internal/deploy/docker.go
  internal/deploy/docker_client.go
  internal/deploy/kubernetes.go
  internal/elasticsearch/client.go
  internal/installer/base.go
  internal/installer/base_test.go
  internal/installer/elasticagent.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_docker.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/kibana/agents.go
  internal/kibana/client.go
  internal/kibana/integrations.go
  internal/kibana/policies.go
  internal/kibana/server.go
  internal/kubernetes/kubernetes.go
  internal/shell/shell.go
  internal/utils/utils.go
  internal/utils/utils_test.go
Labels: backport

#1239 feat: add APM traces for Fleet test suite (#1234) backport for 7.13.x
  .ci/Jenkinsfile
  cli/config/compose/profiles/helm/docker-compose.yml
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest_manager_test.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/fleet/world.go
  e2e/_suites/helm/helm_charts_test.go
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/commons-test.mk
  e2e/steps/befores.go
  internal/common/defaults.go
  internal/deploy/base.go
  internal/deploy/compose.go
  internal/deploy/docker.go
  internal/deploy/docker_client.go
  internal/deploy/kubernetes.go
  internal/elasticsearch/client.go
  internal/installer/base.go
  internal/installer/base_test.go
  internal/installer/elasticagent.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_docker.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/kibana/agents.go
  internal/kibana/client.go
  internal/kibana/integrations.go
  internal/kibana/policies.go
  internal/kibana/server.go
  internal/kubernetes/kubernetes.go
  internal/shell/shell.go
  internal/utils/utils.go
  internal/utils/utils_test.go
Labels: backport

#1240 chore: label beat and stack versions as APM labels
  .ci/Jenkinsfile
Labels: v7.13.0, v7.14.0

#1244 feat: instrument k8s-autodiscover with APM
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
  internal/kubernetes/kubernetes.go
Labels: v7.13.0, v7.14.0

#1249 fix: skip scenarios for standaline with ubi8 images on ARM
  e2e/_suites/fleet/features/stand_alone_agent.feature
Labels: v7.13.0, v7.14.0

#1256 fix: use beat_version as fallback if it's provided
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
  e2e/_suites/metricbeat/metricbeat_test.go
  internal/common/defaults.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_docker.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/utils/utils.go
  internal/utils/utils_test.go
Labels: v7.13.0, v7.14.0

#1258 Support running tests against a remote docker daemon
  cli/config/compose/profiles/fleet/docker-compose.yml
  e2e/_suites/fleet/README.md
  e2e/_suites/fleet/ingest_manager_test.go
  go.mod
  go.sum
  internal/deploy/base.go
  internal/deploy/docker.go
  internal/deploy/docker_client.go
  internal/deploy/kubernetes.go
  internal/kibana/client.go
  internal/kibana/url_prefixes.go
Labels: enhancement, v7.13.0, v7.14.0

#1277 fix: .ci/scripts/push-multiplatform-manifest.sh: not found
  .ci/e2eKibana.groovy
Labels: bug

#1276 Changing minimumHitsCount from 50 to 25
  e2e/_suites/fleet/stand-alone.go
Labels: Team:Automation, enhancement, v7.13.0, v7.14.0

#1281 Re-use bind mounts for kibana docker image
  cli/config/compose/profiles/fleet/docker-compose.yml
Labels: v7.13.0, v7.14.0

#1280 chore: add labels for APM errors
  e2e/_suites/fleet/ingest_manager_test.go
  e2e/_suites/helm/helm_charts_test.go
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: v7.13.0, v7.14.0

#1272 feat: support running elastic-agent alongside Beats
  .ci/.e2e-tests.yaml
  e2e/_suites/fleet/features/running_on_top_of_beats.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/steps/configurations.go
  internal/deploy/base.go
  internal/installer/base.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_docker.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/utils/utils.go
  internal/utils/utils_test.go
Labels: v7.13.0, v7.14.0

#1297 fix: use new method to calculate binary paths in ZIP installer
  internal/installer/elasticagent_zip.go
Labels: v7.13.0, v7.14.0

#1301 fix: use new method to calculate binary paths in ZIP installer (#1297) backport for 7.14.x
  internal/installer/elasticagent_zip.go
Labels: backport

#1290 macOS agent
  go.mod
  go.sum
  internal/installer/base.go
  internal/installer/elasticagent_tar_macos.go
Labels: v7.13.0, v7.14.0

#1304 feat: support MSSQL Server integration in tests
  .ci/.e2e-tests.yaml
  e2e/_suites/metricbeat/features/integrations.feature
  internal/sanitizer/sanitizer.go
  internal/sanitizer/sanitizer_test.go
Labels: v7.13.0, v7.14.0, v7.15.0
