Repository elastic/e2e-testing, pull requests merged in 2021-10, with the labels that each got.

#1627 [automation] update elastic stack version for testing 7.16.0-806be5a9
  .stack-version
Labels: automation, dependency

#1628 feat: run E2E tests for Fleet Server
  .ci/e2eFleetServer.groovy
  .ci/e2eKibana.groovy
  .ci/jobs/fleet-server-e2e-tests.yml
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
  internal/deploy/docker.go
  internal/versions.go
  internal/versions_test.go
Labels: skip_backport

#1632 fix(ci): use the right variable
  .ci/e2eKibana.groovy
Labels: skip_backport

#1634 fix(ci): set base ref for kibana build
  .ci/e2eKibana.groovy
Labels: skip_backport

#1635 [automation] update elastic stack version for testing 8.0.0-2f7ca428
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1637 fix: do not download PRs from Kibana's official repo
  .ci/Jenkinsfile
  e2e/_suites/fleet/ingest_manager_test.go
  internal/common/defaults.go
  internal/deploy/docker_client.go
Labels: v7.14.0, v7.16.0, v7.15.0
