Repository elastic/e2e-testing, pull requests merged in 2021-11, with the labels that each got.

#1743 fix: run local package registry with docker provider
  cli/config/compose/profiles/fleet/default/package-registry.config.yml
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/fleet/preconfigured-policies/package-registry.config.yml
Labels: Team:Automation, v7.16.0, v7.15.0, arm

#1748 [automation] update elastic stack version for testing 7.15.2-5325c15b
  .stack-version
Labels: automation, dependency

#1751 fix: bump elastic-package to v0.27.0
  go.mod
  go.sum
Labels: bug, Team:Automation, v7.16.0, v7.15.0

#1752 fix: use staging env for package registry
  cli/config/compose/profiles/fleet/default/kibana.config.yml
  cli/config/compose/profiles/fleet/preconfigured-policies/kibana.config.yml
  internal/deploy/elastic_package.go
Labels: Team:Automation, backport-skip

#1753 fix: use staging environment for EPR
  cli/config/compose/profiles/fleet/default/kibana.config.yml
  cli/config/compose/profiles/fleet/default/package-registry.config.yml
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/fleet/preconfigured-policies/kibana.config.yml
  cli/config/compose/profiles/fleet/preconfigured-policies/package-registry.config.yml
  internal/deploy/elastic_package.go
Labels: Team:Automation, backport-skip

#1757 fix: use HTTPS protocol for pre-commit hooks
  .pre-commit-config.yaml
Labels: Team:Automation, v7.16.0, v7.15.0

#1756 fix: do not use a local package-registry
  cli/config/compose/profiles/fleet/default/kibana.config.yml
  cli/config/compose/profiles/fleet/default/package-registry.config.yml
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/fleet/preconfigured-policies/kibana.config.yml
  cli/config/compose/profiles/fleet/preconfigured-policies/package-registry.config.yml
  internal/deploy/elastic_package.go
Labels: Team:Automation, backport-skip

#1747 [automation] update elastic stack version for testing 8.1.0-2fdb91c4
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1760 chore: add 8.0 branch to descriptors
  .backportrc.json
  .ci/jobs/e2e-testing-fleet-daily-mbp.yml
  .ci/jobs/e2e-testing-helm-daily-mbp.yml
  .ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml
  .ci/jobs/e2e-testing-mbp.yml
  .mergify.yml
Labels: Team:Automation, backport-skip

#1761 [automation] update elastic stack version for testing 7.15.2-54cb1d1b
  .stack-version
Labels: automation, dependency

#1763 [automation] update elastic stack version for testing 7.16.0-c5c99751
  .stack-version
Labels: automation, dependency

#1764 fix: properly copy files from compose to elastic-package
  internal/deploy/elastic_package.go
Labels: bug, Team:Automation, v8.0.0, v7.16.0, v7.15.0

#1771 [automation] update elastic stack version for testing 8.1.0-96ac1eb1
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1772 [automation] update elastic stack version for testing 8.0.0-decb3f1d
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1770 [automation] update elastic stack version for testing 7.16.0-c51d3b71
  .stack-version
Labels: automation, dependency

#1774 fix: remove preconfigured policies from 7.15
  .ci/.e2e-tests.yaml
  e2e/_suites/fleet/features/preconfigured_policies.feature
Labels: Team:Automation, backport-skip

#1769 [mergify]: use backport-v labels
  .mergify.yml
Labels: automation, backport-skip

#1777 [automation] update elastic stack version for testing 8.0.0-fc3570a9
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1779 [automation] update elastic stack version for testing 8.1.0-f479a40a
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1778 [automation] update elastic stack version for testing 7.15.2-e203d324
  .stack-version
Labels: automation, dependency

#1780 [automation] update elastic stack version for testing 7.16.0-68781827
  .stack-version
Labels: automation, dependency

#1785 chore: remove upgrade tests from 7.15
  e2e/_suites/fleet/features/fleet_mode_agent.feature
Labels: backport-skip

#1786 [automation] update elastic stack version for testing 8.0.0-be754c25
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1789 [automation] update elastic stack version for testing 8.0.0-995d02ee
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1788 [automation] update elastic stack version for testing 7.16.0-df026734
  .stack-version
Labels: automation, dependency

#1790 [automation] update elastic stack version for testing 7.15.2-f9b0a84b
  .stack-version
Labels: automation, dependency

#1792 [mergify] notify to the assignee if PR was not merged yet
  .mergify.yml
Labels: backport-skip

#1795 [automation] update elastic stack version for testing 8.1.0-49c447b0
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1800 [automation] update elastic stack version for testing 8.0.0-31084d02
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1803 [mergify] report open backported PRs once a week
  .mergify.yml
Labels: automation, Team:Automation, backport-skip

#1805 [automation] update elastic stack version for testing 8.0.0-0357b4f0
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1804 [automation] update elastic stack version for testing 8.1.0-14029b3d
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1810 [automation] update elastic stack version for testing 8.1.0-a31f3b73
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1807 chore: stabilise new test scenarios
  .ci/.e2e-tests-for-elastic-agent.yaml
  .ci/.e2e-tests.yaml
  e2e/_suites/fleet/fleet.go
Labels: backport-v7.16.0, backport-v8.0.0

#1809 [automation] update elastic stack version for testing 7.15.3-a6aad1c6
  .stack-version
Labels: automation, dependency

#1808 [automation] update elastic stack version for testing 7.16.0-1af90c36
  .stack-version
Labels: automation, dependency

#1819 fix: use format correctly
  e2e/_suites/fleet/fleet.go
Labels: backport-v7.16.0, backport-v8.0.0

#1820 [automation] update elastic stack version for testing 7.16.0-3a1031bc
  .stack-version
Labels: automation, dependency

#1821 [automation] update elastic stack version for testing 7.15.3-d16f4bc8
  .stack-version
Labels: automation, dependency

#1823 [automation] update elastic stack version for testing 8.1.0-875ad7e2
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1822 [automation] update elastic stack version for testing 8.0.0-1160a953
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1829 Get output files when they have a suffix
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
  e2e/_suites/kubernetes-autodiscover/testdata/templates/filebeat.yml.tmpl
  e2e/_suites/kubernetes-autodiscover/testdata/templates/heartbeat.yml.tmpl
  e2e/_suites/kubernetes-autodiscover/testdata/templates/metricbeat.yml.tmpl
Labels: Team:Integrations, Team:Elastic-Agent-Data-Plane, backport-skip, backport-v8.0.0

#1836 [automation] update elastic stack version for testing 8.0.0-ca68b68a
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1842 [automation] update elastic stack version for testing 8.1.0-a48471bd
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1846 [automation] update elastic stack version for testing 8.0.0-94dc1348
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency

#1845 [automation] update elastic stack version for testing 8.1.0-3307da9c
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1850 [automation] update elastic stack version for testing 8.1.0-3e9afa2a
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#1848 [automation] update elastic stack version for testing 8.0.0-5dc82a0c
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency
