Repository elastic/e2e-testing, pull requests merged in 2021-03, with the labels that each got.

#832 chore: append "-amd64" label for Docker images (#787) backport for 6.8.x
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#830 chore: append "-amd64" label for Docker images (#787) backport for 7.11.x
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#829 chore: append "-amd64" label for Docker images (#787) backport for 7.x
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#831 chore: append "-amd64" label for Docker images (#787) backport for 7.10.x
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: backport

#833 feat: always print agent logs in Fleet mode (#826) backport for 7.x
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
Labels: backport

#834 feat: always print agent logs in Fleet mode (#826) backport for 7.11.x
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
Labels: backport

#835 feat: always print agent logs in Fleet mode (#826) backport for 7.10.x
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
Labels: backport

#836 feat: always print agent logs in Fleet mode (#826) backport for 6.8.x
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
Labels: backport

#837 feat: split backend processes scenarios into a new feature file
  .ci/.e2e-tests.yaml
  e2e/_suites/fleet/features/backend_processes.feature
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/installers.go
Labels: enhancement

#840 feat: split backend processes scenarios into a new feature file (#837) backport for 7.x
  .ci/.e2e-tests.yaml
  e2e/_suites/fleet/features/backend_processes.feature
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/installers.go
Labels: backport

#841 feat: split backend processes scenarios into a new feature file (#837) backport for 7.11.x
  .ci/.e2e-tests.yaml
  e2e/_suites/fleet/features/backend_processes.feature
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/installers.go
Labels: backport

#842 feat: split backend processes scenarios into a new feature file (#837) backport for 7.10.x
  .ci/.e2e-tests.yaml
  e2e/_suites/fleet/features/backend_processes.feature
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/installers.go
Labels: backport

#843 feat: split backend processes scenarios into a new feature file (#837) backport for 6.8.x
  .ci/.e2e-tests.yaml
  e2e/_suites/fleet/features/backend_processes.feature
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/installers.go
Labels: backport

#844 chore: notify upstream PR/branch the soonest (#839) backport for 7.x
  .ci/Jenkinsfile
Labels: backport

#845 chore: notify upstream PR/branch the soonest (#839) backport for 7.11.x
  .ci/Jenkinsfile
Labels: backport

#846 chore: notify upstream PR/branch the soonest (#839) backport for 7.10.x
  .ci/Jenkinsfile
Labels: backport

#847 chore: notify upstream PR/branch the soonest (#839) backport for 6.8.x
  .ci/Jenkinsfile
Labels: backport

#850 fix: resolve metricbeat base version in the case it's an alias (#849) backport for 7.x
  .ci/Jenkinsfile
  .ci/scripts/functional-test.sh
  .ci/scripts/metricbeat-test.sh
  e2e/Makefile
  e2e/README.md
  e2e/_suites/fleet/README.md
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/metricbeat/README.md
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/utils_test.go
Labels: backport

#853 fix: resolve metricbeat base version in the case it's an alias (#849) backport for 6.8.x
  .ci/Jenkinsfile
  .ci/scripts/functional-test.sh
  .ci/scripts/metricbeat-test.sh
  e2e/Makefile
  e2e/README.md
  e2e/_suites/fleet/README.md
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/metricbeat/README.md
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/utils_test.go
Labels: backport

#851 fix: resolve metricbeat base version in the case it's an alias (#849) backport for 7.11.x
  .ci/Jenkinsfile
  .ci/scripts/functional-test.sh
  .ci/scripts/metricbeat-test.sh
  e2e/Makefile
  e2e/README.md
  e2e/_suites/fleet/README.md
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/metricbeat/README.md
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/utils_test.go
Labels: backport

#852 fix: resolve metricbeat base version in the case it's an alias (#849) backport for 7.10.x
  .ci/Jenkinsfile
  .ci/scripts/functional-test.sh
  .ci/scripts/metricbeat-test.sh
  e2e/Makefile
  e2e/README.md
  e2e/_suites/fleet/README.md
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/metricbeat/README.md
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/utils_test.go
Labels: backport

#860 feat: instrument Helm charts test suite (#858) backport for 7.x
  cli/cmd/run.go
  cli/cmd/stop.go
  cli/config/compose/profiles/helm/docker-compose.yml
  cli/docker/docker.go
  cli/services/helm.go
  cli/services/kibana.go
  cli/services/kubectl.go
  cli/services/manager.go
  cli/shell/shell.go
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/helm/helm_charts_test.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/elasticsearch.go
  e2e/steps/befores.go
Labels: backport

#861 feat: instrument Helm charts test suite (#858) backport for 7.12.x
  cli/cmd/run.go
  cli/cmd/stop.go
  cli/config/compose/profiles/helm/docker-compose.yml
  cli/docker/docker.go
  cli/services/helm.go
  cli/services/kibana.go
  cli/services/kubectl.go
  cli/services/manager.go
  cli/shell/shell.go
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/helm/helm_charts_test.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/elasticsearch.go
  e2e/steps/befores.go
Labels: backport

#862 feat: instrument Helm charts test suite (#858) backport for 7.11.x
  cli/cmd/run.go
  cli/cmd/stop.go
  cli/config/compose/profiles/helm/docker-compose.yml
  cli/docker/docker.go
  cli/services/helm.go
  cli/services/kibana.go
  cli/services/kubectl.go
  cli/services/manager.go
  cli/shell/shell.go
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/helm/helm_charts_test.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/elasticsearch.go
  e2e/steps/befores.go
Labels: backport

#863 feat: instrument Helm charts test suite (#858) backport for 6.8.x
  cli/cmd/run.go
  cli/cmd/stop.go
  cli/config/compose/profiles/helm/docker-compose.yml
  cli/docker/docker.go
  cli/services/helm.go
  cli/services/kibana.go
  cli/services/kubectl.go
  cli/services/manager.go
  cli/shell/shell.go
  e2e/_suites/fleet/ingest-manager_test.go
  e2e/_suites/helm/helm_charts_test.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/elasticsearch.go
  e2e/steps/befores.go
Labels: backport

#872 fix: use proper flags (#868) backport for 6.8.x
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
Labels: backport

#871 fix: use proper flags (#868) backport for 7.12.x
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
Labels: backport

#870 fix: use proper flags (#868) backport for 7.x
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
Labels: backport

#866 break: move from "pull-requests" to "commits" GCP bucket
  e2e/Makefile
  e2e/README.md
  e2e/_suites/fleet/README.md
  e2e/_suites/fleet/installers.go
  e2e/_suites/metricbeat/README.md
  e2e/_testresources/gcp/commits.json
  e2e/_testresources/gcp/pull-requests.json
  e2e/utils.go
  e2e/utils_test.go
Labels: P1, breaking-change, bug

#876 break: move from "pull-requests" to "commits" GCP bucket (#866) backport for 7.12.x
  e2e/Makefile
  e2e/README.md
  e2e/_suites/fleet/README.md
  e2e/_suites/fleet/installers.go
  e2e/_suites/metricbeat/README.md
  e2e/_testresources/gcp/commits.json
  e2e/_testresources/gcp/pull-requests.json
  e2e/utils.go
  e2e/utils_test.go
Labels: backport

#875 break: move from "pull-requests" to "commits" GCP bucket (#866) backport for 7.x
  e2e/Makefile
  e2e/README.md
  e2e/_suites/fleet/README.md
  e2e/_suites/fleet/installers.go
  e2e/_suites/metricbeat/README.md
  e2e/_testresources/gcp/commits.json
  e2e/_testresources/gcp/pull-requests.json
  e2e/utils.go
  e2e/utils_test.go
Labels: backport

#882 feat: run most frequent flavours in the PR stage (#873) backport for 7.11.x
  .ci/.e2e-tests.yaml
  .ci/Jenkinsfile
  e2e/_suites/fleet/features/agent_endpoint_integration.feature
  e2e/_suites/fleet/features/backend_processes.feature
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/features/stand_alone_agent.feature
  e2e/_suites/metricbeat/features/integrations.feature
Labels: backport

#881 feat: run most frequent flavours in the PR stage (#873) backport for 7.12.x
  .ci/.e2e-tests.yaml
  .ci/Jenkinsfile
  e2e/_suites/fleet/features/agent_endpoint_integration.feature
  e2e/_suites/fleet/features/backend_processes.feature
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/features/stand_alone_agent.feature
  e2e/_suites/metricbeat/features/integrations.feature
Labels: backport

#880 feat: run most frequent flavours in the PR stage (#873) backport for 7.x
  .ci/.e2e-tests.yaml
  .ci/Jenkinsfile
  e2e/_suites/fleet/features/agent_endpoint_integration.feature
  e2e/_suites/fleet/features/backend_processes.feature
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/_suites/fleet/features/stand_alone_agent.feature
  e2e/_suites/metricbeat/features/integrations.feature
Labels: backport

#877 break: move from "pull-requests" to "commits" GCP bucket (#866) backport for 7.11.x
  e2e/Makefile
  e2e/README.md
  e2e/_suites/fleet/README.md
  e2e/_suites/fleet/installers.go
  e2e/_suites/metricbeat/README.md
  e2e/_testresources/gcp/commits.json
  e2e/_testresources/gcp/pull-requests.json
  e2e/utils.go
  e2e/utils_test.go
Labels: backport

#887 docs: add Make as build system (#886) backport for 7.x
  e2e/README.md
Labels: backport

#889 docs: add Make as build system (#886) backport for 7.11.x
  e2e/README.md
Labels: backport

#888 docs: add Make as build system (#886) backport for 7.12.x
  e2e/README.md
Labels: backport

#885 [CI] tear down the workspace
  .ci/Jenkinsfile
Labels: automation, ci

#874 chore: bump helm versions
  .ci/Jenkinsfile
  .ci/scripts/install-helm-test-dependencies.sh
  e2e/_suites/helm/README.md
  e2e/_suites/helm/helm_charts_test.go
Labels: helm

#896 chore: bump helm versions (#874) backport for 7.x
  .ci/Jenkinsfile
  .ci/scripts/install-helm-test-dependencies.sh
  e2e/_suites/helm/README.md
  e2e/_suites/helm/helm_charts_test.go
Labels: backport

#898 chore: bump helm versions (#874) backport for 7.11.x
  .ci/Jenkinsfile
  .ci/scripts/install-helm-test-dependencies.sh
  e2e/_suites/helm/README.md
  e2e/_suites/helm/helm_charts_test.go
Labels: backport

#897 chore: bump helm versions (#874) backport for 7.12.x
  .ci/Jenkinsfile
  .ci/scripts/install-helm-test-dependencies.sh
  e2e/_suites/helm/README.md
  e2e/_suites/helm/helm_charts_test.go
Labels: backport

#893 [CI] tear down the workspace (#885) backport for 7.11.x
  .ci/Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#892 [CI] tear down the workspace (#885) backport for 7.12.x
  .ci/Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#891 [CI] tear down the workspace (#885) backport for 7.x
  .ci/Jenkinsfile
Labels: Team:Automation, automation, backport, ci

#902 chore: rename slack channel for Fleet's nightly build (#899) backport for 7.x
  .ci/e2eTestingFleetDaily.groovy
Labels: backport

#903 chore: rename slack channel for Fleet's nightly build (#899) backport for 7.12.x
  .ci/e2eTestingFleetDaily.groovy
Labels: backport

#904 chore: rename slack channel for Fleet's nightly build (#899) backport for 7.11.x
  .ci/e2eTestingFleetDaily.groovy
Labels: backport

#910 fix: generate a jUnit file per test suite (#907) backport for 7.11.x
  .ci/scripts/build-test.sh
  cli/Makefile
  commons.mk
  e2e/Makefile
Labels: backport

#909 fix: generate a jUnit file per test suite (#907) backport for 7.12.x
  .ci/scripts/build-test.sh
  cli/Makefile
  commons.mk
  e2e/Makefile
Labels: backport

#908 fix: generate a jUnit file per test suite (#907) backport for 7.x
  .ci/scripts/build-test.sh
  cli/Makefile
  commons.mk
  e2e/Makefile
Labels: backport

#912 fix: bump stale agent version to 7.11-SNAPSHOT
  .ci/Jenkinsfile
  e2e/_suites/fleet/ingest-manager_test.go
Labels: bug

#913 chore: follow Golang's best practices (#865) backport for 7.x
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest_manager_test.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/fleet/world.go
  e2e/steps/befores.go
  e2e/steps/processes.go
  e2e/steps/services.go
Labels: backport

#914 chore: follow Golang's best practices (#865) backport for 7.12.x
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest_manager_test.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/fleet/world.go
  e2e/steps/befores.go
  e2e/steps/processes.go
  e2e/steps/services.go
Labels: backport

#915 chore: follow Golang's best practices (#865) backport for 7.11.x
  .ci/Jenkinsfile
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest_manager_test.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/fleet/services.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/fleet/world.go
  e2e/steps/befores.go
  e2e/steps/processes.go
  e2e/steps/services.go
Labels: backport

#916 Update missing instruction for functional-test
  e2e/_suites/fleet/README.md
Labels: documentation

#920 Update missing instruction for functional-test (#916) backport for 7.11.x
  e2e/_suites/fleet/README.md
Labels: backport

#918 Update missing instruction for functional-test (#916) backport for 7.x
  e2e/_suites/fleet/README.md
Labels: backport

#919 Update missing instruction for functional-test (#916) backport for 7.12.x
  e2e/_suites/fleet/README.md
Labels: backport

#917 ci: use the new flaky analyser
  .ci/Jenkinsfile
Labels: automation, ci, v7.11.0, v7.12.0, v7.13.0

#924 Add basic tests for the Linux integration
  cli/services/kibana.go
  e2e/_suites/fleet/features/linux_integration.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/integrations.go
Labels: enhancement, v7.11.0, v7.12.0, v7.13.0

#935 Update readme with correct service versions and profile
  cli/README.md
Labels: documentation, v7.11.0, v7.12.0, v7.13.0

#934 fix: pass platform version to metricbeat, not to the integration
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: bug, v7.11.0, v7.12.0, v7.13.0

#949 fix: retry tagging the loaded docker image up-to 15 seconds
  cli/docker/docker.go
  e2e/_suites/fleet/installers.go
  e2e/_suites/metricbeat/metricbeat_test.go
Labels: bug, v7.11.0, v7.12.0, v7.13.0

#943 cli: enable loading default profiles turnkey
  cli/NOTICE.txt
  cli/cmd/deploy.go
  cli/cmd/run.go
  cli/cmd/stop.go
  cli/cmd/sync.go
  cli/config/compose/profiles/fleet/configurations/kibana.config.yml
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/config.go
  cli/go.mod
  cli/go.sum
  e2e/_suites/fleet/ingest_manager_test.go
Labels: enhancement

#957 Add basic check on correct service is defined for profile runs
  cli/cmd/run.go
Labels: bug

#954 Consolidate go modules to top level directory
  cli/go.mod
  cli/go.sum
  doc.go
  e2e/go.mod
  e2e/go.sum
  go.mod
  go.sum
Labels: v7.11.0, v7.12.0, v7.13.0

#966 fix: use PRs configuration files (#956) backport for 7.11.x
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/steps/configurations.go
  e2e/utils.go
Labels: backport

#965 fix: use PRs configuration files (#956) backport for 7.12.x
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/steps/configurations.go
  e2e/utils.go
Labels: backport

#964 fix: use PRs configuration files (#956) backport for 7.x
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/metricbeat/metricbeat_test.go
  e2e/steps/configurations.go
  e2e/utils.go
Labels: backport

#968 ci: use withNode step to avoid reusing workers
  .ci/Jenkinsfile
Labels: backport, v7.11.0, v7.12.0, v7.13.0

#970 ci: use a top level ephemeral worker
  .ci/Jenkinsfile
Labels: v7.11.0, v7.12.0, v7.13.0

#978 Add a standalone test scenario for fleet server mode
  cli/config/compose/services/elastic-agent/docker-compose.yml
  e2e/_suites/fleet/features/stand_alone_agent.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/stand-alone.go
Labels: enhancement

#977 Build binaries via goreleaser
  .gitignore
  .goreleaser.yml
  Makefile
  README.md
  cli/.gitignore
  cli/Building.md
  cli/Makefile
  cli/scripts/build-cli.sh
Labels: enhancement
