Repository elastic/e2e-testing, pull requests merged in 2022-09, with the labels that each got.

#2980 action: Sync main with feature-arch-v2
  .github/workflows/sync-branches.yml
Labels: automation, backport-skip

#2999 Fix testcases for fleet api
  e2e/_suites/fleet/testresources/default_system_metrics.json
  e2e/_suites/fleet/testresources/linux_metrics.json
Labels: backport-v8.0.0, backport-v8.3.0, backport-v8.4.0

#2975 Adding support for v1.25.0 k8s
  .ci/Jenkinsfile
  .ci/scripts/install-helm-test-dependencies.sh
  .ci/scripts/install-kubernetes-autodiscover-test-dependencies.sh
  .stack-version
  e2e/_suites/helm/README.md
  e2e/_suites/helm/helm_charts_test.go
  e2e/_suites/kubernetes-autodiscover/README.md
  e2e/_suites/kubernetes-autodiscover/testdata/templates/a-short-living-cronjob.yml.tmpl
  internal/config/kubernetes/README.md
Labels: backport-skip

#2772 chore: stringify http responses
  internal/kibana/agents.go
  internal/kibana/integrations.go
  internal/kibana/policies.go
  internal/kibana/server.go
Labels: area:test, backport-v8.3.0, backport-v7.17.0, backport-v8.4.0

#3023 Update ingest notifications channel
  .ci/e2eTestingFleetDaily.groovy
  .ci/e2eTestingMacosDaily.groovy
Labels: backport-skip

#2929 Making Changes for Improving the guide for troubleshooting E2E setup errors
  .ci/README.md
  .ci/ansible/tasks/install_deps.yml
Labels: backport-skip

#3043 Added support for bulk api update change
  e2e/_suites/fleet/api_keys.go
  e2e/_suites/fleet/features/permission_output_change.feature
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/fleet_test.go
  internal/elasticsearch/client.go
  internal/kibana/agents.go
Labels: backport-v8.5.0

#3048 fix: added setuptools-rust to requiremets.txt
  .ci/Makefile
  .ci/ansible/playbook.yml
Labels: backport-skip
