Repository elastic/e2e-testing, pull requests merged in 2022-04, with the labels that each got.

#2310 [automation] update elastic stack version for testing 8.3.0-1ecd9720
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2311 [automation] update elastic stack version for testing 8.1.2-ed029c28
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2312 [automation] update elastic stack version for testing 7.17.3-22be2d34
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2309 [automation] update elastic stack version for testing 8.2.0-5d1042d1
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2293 chore: start sending OTEL traces for the e2e
  .ci/Jenkinsfile
Labels: enhancement, Team:Automation, area:test, backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#2317 [automation] update elastic stack version for testing 8.3.0-4cd86339
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2319 [automation] update elastic stack version for testing 7.17.3-42e5086c
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2318 [automation] update elastic stack version for testing 8.2.0-f531236e
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2327 fix: send slack notifications for failed builds
  .ci/Jenkinsfile
Labels: bug, Team:Automation, area:ci, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#2320 [automation] update elastic stack version for testing 8.3.0-657f2d50
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2323 [automation] update elastic stack version for testing 7.17.3-206df1ed
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2331 chore: backport settings
  .backportrc.json
  .ci/jobs/e2e-testing-fleet-daily-mbp.yml
  .ci/jobs/e2e-testing-helm-daily-mbp.yml
  .ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml
  .ci/jobs/e2e-testing-mbp.yml
  .mergify.yml
Labels: Team:Automation, area:ci, backport-skip

#2332 [automation] update elastic stack version for testing 8.1.3-c3f4b7e6
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2335 [automation] update elastic stack version for testing 7.17.3-60b577ee
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2344 fix: bump stale agent to 7.17.2
  .ci/Jenkinsfile
  internal/common/defaults.go
Labels: Team:Automation, area:test, dependency, backport-skip

#2345 chore: add reliability to fleet-server's bootstrap
  .ci/Jenkinsfile
  e2e/_suites/fleet/fleet.go
  go.mod
  go.sum
  internal/deploy/elastic_package.go
Labels: Team:Automation, area:test, area:ci, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#2350 [automation] update elastic stack version for testing 7.17.3-2d046908
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2355 [automation] update elastic stack version for testing 8.3.0-8d19ff01
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2357 [automation] update elastic stack version for testing 7.17.3-4c0e3956
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2356 [automation] update elastic stack version for testing 8.2.0-bcbc1a13
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2358 [automation] update elastic stack version for testing 8.1.3-91a16370
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2359 chore: add 8 next-minor to the scheduled builds
  .ci/schedule-daily.groovy
Labels: Team:Automation, area:ci, backport-skip

#2360 [automation] update elastic stack version for testing 8.3.0-2c8f9574
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2361 [automation] update elastic stack version for testing 8.1.3-9689383f
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2362 [automation] update elastic stack version for testing 7.17.3-860249fc
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2363 [automation] update elastic stack version for testing 8.2.0-a99722cc
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2365 [automation] update elastic stack version for testing 7.17.3-b688e1c0
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2364 [automation] update elastic stack version for testing 8.1.3-f8a17b61
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2366 Add AndersonQ to github-ssh-keys
  .ci/ansible/github-ssh-keys
Labels: enhancement, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#2371 [automation] update elastic stack version for testing 8.1.3-bb164e02
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2373 [automation] update elastic stack version for testing 7.17.3-d599ee07
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2375 [automation] update elastic stack version for testing 8.2.0-edf55ea1
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2377 [automation] update elastic stack version for testing 7.17.3-a0d290fb
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2374 [automation] update elastic stack version for testing 8.3.0-55ba6f37
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2376 [automation] update elastic stack version for testing 8.1.3-5c80e943
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2379 [automation] update elastic stack version for testing 8.2.0-c65cb8e3
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2380 [automation] update elastic stack version for testing 7.17.3-feda78d8
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2378 [automation] update elastic stack version for testing 8.3.0-c655cda8
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2381 [automation] update elastic stack version for testing 8.1.3-28740185
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2382 [automation] update elastic stack version for testing 8.2.0-3a7e2f99
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2384 [automation] update elastic stack version for testing 8.1.3-2a8b1f31
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2387 fix: add EOF
  .ci/ansible/github-ssh-keys
Labels: backport-skip

#2389 chore: add narph to ssh users
  .ci/ansible/github-ssh-keys
Labels: area:ci, backport-skip

#2390 chore: add narph to ssh users (#2389)
  .ci/ansible/github-ssh-keys
Labels: Team:Automation, area:ci, backport-skip

#2391 chore: add narph to ssh users (#2389)
  .ci/ansible/github-ssh-keys
Labels: Team:Automation, area:ci, backport-skip

#2394 [automation] update elastic stack version for testing 8.2.0-a7e9513d
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2396 [automation] update elastic stack version for testing 7.17.3-b148b9ca
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2395 [automation] update elastic stack version for testing 8.1.3-0c4e7b42
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2392 Add link to the users used to SSH into the Cloud EC2s
  e2e/TROUBLESHOOTING.md
Labels: documentation, area:documentation, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#2401 [automation] update elastic stack version for testing 7.17.3-e9aee937
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2411 [automation] update elastic stack version for testing 8.2.0-c47183cf
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2408 [automation] update elastic stack version for testing 8.1.4-4911e5d4
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2410 [automation] update elastic stack version for testing 7.17.4-51efa5cc
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2414 [automation] update elastic stack version for testing 8.2.0-14a8abdc
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2415 [automation] update elastic stack version for testing 7.17.4-4d7a6e74
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2413 [automation] update elastic stack version for testing 8.1.4-bc369beb
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2407 Add metadata tags
  .ci/Jenkinsfile
  .ci/ansible/playbook.yml
  .ci/ansible/tasks/runners.yml
  .ci/aws-instances-reaper.groovy
Labels: automation, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#2419 ci: transform branch to allow the Google Labels naming
  .ci/Jenkinsfile
Labels: backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#2422 [automation] update elastic stack version for testing 8.2.0-63f66f47
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2421 [automation] update elastic stack version for testing 8.1.4-96de35ab
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2424 [automation] update elastic stack version for testing 7.17.4-073e030e
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2429 fix: use "0.0.0.0" string instead of null for ES' network.host
  cli/config/compose/profiles/fleet/docker-compose.yml
  e2e/templates/profile.yml.tmpl
Labels: Team:Automation, backport-skip

#2266 docs: revamp
  .ci/README.md
  .github/ISSUE_TEMPLATE/new-platform-support.yml
  e2e/README.md
  e2e/_suites/fleet/README.md
  e2e/_suites/kubernetes-autodiscover/README.md
  e2e/tooling.md
Labels: Team:Automation, area:documentation, backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#2404 docs: document the process of running the tests in the cloud machines
  e2e/TROUBLESHOOTING.md
Labels: Team:Automation, area:test, area:ci, area:documentation, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#2433 [automation] update elastic stack version for testing 7.17.4-a30db1f9
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2445 how to run tests a single scenario
  e2e/_suites/kubernetes-autodiscover/README.md
  e2e/_suites/kubernetes-autodiscover/features/elastic_agent_standalone.feature
Labels: documentation, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#2449 [automation] update elastic stack version for testing 8.3.0-194e3512
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2451 [automation] update elastic stack version for testing 8.1.4-7b3e4fd0
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2452 [automation] update elastic stack version for testing 7.17.4-40d3b33d
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip
