Repository elastic/e2e-testing, pull requests merged in 2022-01, with the labels that each got.

#1967 [automation] update elastic stack version for testing 7.17.0-343e3146
  .stack-version
Labels: automation, dependency, backport-skip

#1943 feat: export Fetch&Download methods in the /pkg directory
  Makefile
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
  internal/common/defaults.go
  internal/deploy/docker.go
  internal/deploy/docker_test.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_docker.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/installer/elasticagent_tar_macos.go
  internal/installer/elasticagent_zip.go
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-aarch64.rpm
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-amd64.deb
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-arm64.deb
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-amd64.docker.tar.gz
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-amd64.tar.gz
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-arm64.docker.tar.gz
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-arm64.tar.gz
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-x86_64.tar.gz
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-x86_64.rpm
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-ubi8-BEATS_VERSION-linux-amd64.docker.tar.gz
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-ubi8-BEATS_VERSION-linux-arm64.docker.tar.gz
  pkg/_testresources/gcp/commits.json
  pkg/_testresources/gcp/nextPageParam.json
  pkg/_testresources/gcp/snapshots.json
  pkg/downloads/versions.go
  pkg/downloads/versions_test.go
Labels: Team:Automation, backport-v7.16.0, backport-v8.0.0, backport-v7.17.0

#1973 [automation] update elastic stack version for testing 7.17.0-b402b9a8
  .stack-version
Labels: automation, dependency, backport-skip

#1979 [automation] update elastic stack version for testing 7.17.0-32e424af
  .stack-version
Labels: automation, dependency, backport-skip

#1981 [automation] update elastic stack version for testing 7.17.0-fe65ce80
  .stack-version
Labels: automation, dependency, backport-skip

#1959 chore: bump elastic-package to v0.32.1
  .ci/ansible/playbook.yml
  .go-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  go.mod
  go.sum
Labels: backport-v8.0.0

#1988 [automation] update elastic stack version for testing 7.17.0-9b8314f9
  .stack-version
Labels: automation, dependency, backport-skip

#1990 chore: add resiliency when provisioning the stack
  .ci/Jenkinsfile
Labels: Team:Automation, priority:medium, size:S, area:ci, impact:low, backport-v7.16.0, backport-v8.0.0, backport-v7.17.0

#1995 [automation] update elastic stack version for testing 7.17.0-2435c356
  .stack-version
Labels: automation, dependency, backport-skip

#1999 [automation] update elastic stack version for testing 7.17.0-049bcf23
  .stack-version
Labels: automation, dependency, backport-skip

#2005 [automation] update elastic stack version for testing 7.17.0-079761a0
  .stack-version
Labels: automation, dependency, backport-skip

#1984 Update `fetchBeatsBinary` to be reused in elastic-agent-poc
  internal/utils/utils.go
  internal/utils/utils_test.go
  pkg/downloads/versions.go
  pkg/downloads/versions_test.go
Labels: backport-v7.16.0, backport-v8.0.0, backport-v7.17.0

#2014 chore: bump stale agent for main
  .ci/Jenkinsfile
  internal/common/defaults.go
Labels: backport-skip

#2013 chore: bump stale agent for 8.0
  .ci/Jenkinsfile
  internal/common/defaults.go
Labels: skip_backport, backport-skip

#2017 chore: bump 7.16 version to use snapshots
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  internal/common/defaults.go
Labels: backport-skip

#2015 chore: remove upgrade test for 7.16
  e2e/_suites/fleet/features/fleet_mode_agent.feature
Labels: backport-skip

#2020 [automation] update elastic stack version for testing 7.17.0-68da5d12
  .stack-version
Labels: automation, dependency, backport-skip

#2007 SLES15 enablement
  .ci/.e2e-tests-for-elastic-agent.yaml
  .ci/.e2e-tests.yaml
  .ci/Jenkinsfile
  .ci/ansible/playbook.yml
  .ci/ansible/tasks/copy_test_files.yml
  .ci/ansible/tasks/install_deps.yml
  .ci/ansible/tasks/runners.yml
  .ci/ansible/tasks/setup_test_script.yml
Labels: v8.1.0, backport-v8.0.0, backport-v7.17.0

#2024 [7.17](backport #2007) SLES15 enablement
  .ci/.e2e-tests-for-elastic-agent.yaml
  .ci/.e2e-tests.yaml
  .ci/Jenkinsfile
  .ci/ansible/playbook.yml
  .ci/ansible/tasks/copy_test_files.yml
  .ci/ansible/tasks/install_deps.yml
  .ci/ansible/tasks/runners.yml
  .ci/ansible/tasks/setup_test_script.yml
Labels: backport-skip

#2025 fix: use the right branch for 7.17 backports
  .mergify.yml
Labels: backport-skip

#2027 bump stack version 7.17.0-5ce40764
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  internal/common/defaults.go
Labels: Team:Automation, backport-skip

#2028 [automation] update elastic stack version for testing 7.17.0-e1efbe3a
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2001 feat: enable SSH access to users for debugging cloud instances
  .ci/Jenkinsfile
  .ci/ansible/github-ssh-keys
  .ci/ansible/playbook.yml
  .ci/ansible/tasks/install_deps.yml
  .ci/ansible/tasks/install_ssh_keys.yml
  .ci/ansible/tasks/runners.yml
  .ci/aws-instances-reaper.groovy
  .ci/jobs/aws-instances-reaper.yml
  .ci/scripts/import-ssh-keys.sh
  e2e/TROUBLESHOOTING.md
Labels: backport-v7.16.0, backport-v8.0.0, backport-v7.17.0

#2031 feat: enable SSH access to users for debugging cloud instances (#2001) backport for 7.17
  .ci/Jenkinsfile
  .ci/ansible/github-ssh-keys
  .ci/ansible/playbook.yml
  .ci/ansible/tasks/install_deps.yml
  .ci/ansible/tasks/install_ssh_keys.yml
  .ci/ansible/tasks/runners.yml
  .ci/aws-instances-reaper.groovy
  .ci/jobs/aws-instances-reaper.yml
  .ci/scripts/import-ssh-keys.sh
  e2e/TROUBLESHOOTING.md
Labels: backport

#2030 feat: enable SSH access to users for debugging cloud instances (#2001) backport for 8.0
  .ci/Jenkinsfile
  .ci/ansible/github-ssh-keys
  .ci/ansible/playbook.yml
  .ci/ansible/tasks/install_deps.yml
  .ci/ansible/tasks/install_ssh_keys.yml
  .ci/ansible/tasks/runners.yml
  .ci/aws-instances-reaper.groovy
  .ci/jobs/aws-instances-reaper.yml
  .ci/scripts/import-ssh-keys.sh
  e2e/TROUBLESHOOTING.md
Labels: backport

#2040 [automation] update elastic stack version for testing 7.17.0-1bd58b32
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2041 [automation] update elastic stack version for testing 7.16.4-206b88b5
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2044 chore: split stack configuration and start into two tasks
  .ci/ansible/playbook.yml
Labels: backport-v7.16.0, backport-v8.0.0, backport-v7.17.0

#2032 feat: enable SSH access to users for debugging cloud instances (#2001) backport for 7.16
  .ci/Jenkinsfile
  .ci/ansible/github-ssh-keys
  .ci/ansible/playbook.yml
  .ci/ansible/tasks/install_deps.yml
  .ci/ansible/tasks/install_ssh_keys.yml
  .ci/ansible/tasks/runners.yml
  .ci/aws-instances-reaper.groovy
  .ci/jobs/aws-instances-reaper.yml
  .ci/scripts/import-ssh-keys.sh
  e2e/TROUBLESHOOTING.md
Labels: backport

#2048 chore: use Ansible's built-in replace instead of sed
  .ci/ansible/playbook.yml
Labels: backport-v7.16.0, backport-v8.0.0, backport-v7.17.0

#2053 fix: set default region for AWS cli
  .ci/aws-instances-reaper.groovy
Labels: backport-skip

#2034 feat: add CentOS 8 support
  .ci/.e2e-tests-for-elastic-agent.yaml
  .ci/.e2e-tests.yaml
  .ci/Jenkinsfile
  .ci/ansible/playbook.yml
  .ci/ansible/tasks/setup_test_script.yml
Labels: Team:Automation, area:ci, backport-v7.16.0, backport-v8.0.0, backport-v7.17.0

#2057 chore: rename Jenkins stage to include suite
  .ci/.e2e-tests-for-elastic-agent.yaml
  .ci/.e2e-tests.yaml
  .ci/Jenkinsfile
Labels: backport-v7.16.0, backport-v8.0.0, backport-v7.17.0

#2066 chore: double wait time for SSH
  .ci/Jenkinsfile
  .ci/ansible/ansible.cfg
  .ci/ansible/tasks/wait_for_ssh.yml
Labels: backport-v7.16.0, backport-v8.0.0, backport-v7.17.0

#2070 fix: use ansible.cfg in the right path
  .ci/Jenkinsfile
  .ci/ansible/requirements.txt
  .ci/ansible/tasks/wait_for_ssh.yml
Labels: backport-v7.16.0, backport-v8.0.0, backport-v7.17.0

#2075 chore: always install tools in runners
  .ci/ansible/playbook.yml
  .ci/ansible/tasks/setup_test_script.yml
Labels: backport-v7.16.0, backport-v8.0.0, backport-v7.17.0

#2077 [automation] update elastic stack version for testing 8.1.0-aa69d697
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip
