Repository elastic/e2e-testing, pull requests merged in 2022-07, with the labels that each got.

#2748 fix: consistently read versions in Ansible
  .ci/Jenkinsfile
  .ci/ansible/tasks/setup_test_script.yml
  .ci/ansible/tasks/setup_test_script_windows.yml
Labels: bug, Team:Automation, area:test, area:ci, backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2718 chore: use DEVELOPER_MODE to not uninstall/unenroll the agent
  .ci/README.md
  .ci/ansible/tasks/setup_test_script.yml
  .ci/ansible/tasks/setup_test_script_windows.yml
  e2e/_suites/fleet/fleet.go
Labels: Team:Automation, area:test, backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2763 [automation] update elastic stack version for testing 8.3.2-d34285fd
  .ci/Jenkinsfile
  .ci/e2eTestingMacosDaily.groovy
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2765 [automation] update elastic stack version for testing 7.17.6-1e4f9cbf
  .ci/Jenkinsfile
  .ci/e2eTestingMacosDaily.groovy
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2766 [automation] update elastic stack version for testing 8.2.4-e7c42e26
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2767 [automation] update elastic stack version for testing 8.3.2-56253b46
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2769 [automation] update elastic stack version for testing 8.3.2-97fdd78b
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2770 [automation] update elastic stack version for testing 7.17.6-94c92680
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2773 chore: increase max test timeout in 'go test' command
  .ci/ansible/tasks/setup_test_script_windows.yml
  e2e/_suites/fleet/README.md
  e2e/_suites/helm/README.md
  e2e/_suites/kubernetes-autodiscover/README.md
  e2e/commons-test.mk
Labels: area:test, backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2778 [automation] update elastic stack version for testing 8.3.3-385d4fdb
  .ci/Jenkinsfile
  .ci/e2eTestingMacosDaily.groovy
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2780 [automation] update elastic stack version for testing 8.3.3-46b07667
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2490 chore: use build system to create the VMs on CI
  .ci/Jenkinsfile
  .ci/Makefile
  .ci/README.md
  .ci/ansible/elastic-stack.yml
  .ci/ansible/fetch-test-reports.yml
  .ci/ansible/files/sshd_config
  .ci/ansible/playbook.yml
  .ci/ansible/tasks/copy_test_files.yml
  .ci/ansible/tasks/fetch_test_reports.yml
  .ci/ansible/tasks/runners.yml
  .ci/ansible/tasks/setup_test_script.yml
  .ci/ansible/tasks/setup_test_script_windows.yml
  .ci/ansible/tasks/teardown.yml
  .ci/ansible/teardown.yml
  .ci/scripts/functional-test.sh
  .ci/scripts/generate-cucumber-reports.sh
  .ci/scripts/yq.sh
  .gitignore
  e2e/TROUBLESHOOTING.md
Labels: Team:Automation, area:ci, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#2786 fix: do not destroy machines from concurrent builds
  .ci/Jenkinsfile
  .ci/Makefile
Labels: bug, Team:Automation, area:ci, backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2790 [automation] update elastic stack version for testing 7.17.6-5c77e057
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2791 [automation] update elastic stack version for testing 8.3.3-0264aa15
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2793 chore: remove verbosity in SSH connections
  .ci/Makefile
Labels: Team:Automation, area:test, backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2797 [automation] update elastic stack version for testing 7.17.6-a62286d6
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2807 [automation] update elastic stack version for testing 8.4.0-a324b98b
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2809 [automation] update elastic stack version for testing 8.3.3-302be7c1
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2811 feat(ci): support passing a commit SHA to run the MacOS tests
  .ci/Jenkinsfile
  .ci/e2eTestingMacosDaily.groovy
Labels: backport-v8.3.0

#2814 [automation] update elastic stack version for testing 7.17.6-0f95e383
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2813 [automation] update elastic stack version for testing 8.3.3-e5bc7e69
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2815 [automation] update elastic stack version for testing 8.4.0-31269fd2
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2817 fix: increase instance size to 15Gb
  .ci/ansible/tasks/runners.yml
  internal/kibana/agents.go
Labels: bug, area:ci, backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2823 [automation] update elastic stack version for testing 8.3.3-508a8f45
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2824 [automation] update elastic stack version for testing 7.17.6-7ad6b445
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2825 chore: simplify CI matrix for managing integrations in policies
  .ci/.e2e-tests-beats.yaml
  .ci/.e2e-tests-daily.yaml
  .ci/.e2e-tests-for-elastic-agent.yaml
  .ci/.e2e-tests.yaml
  e2e/QUICKSTART.md
  e2e/_suites/fleet/features/manage_integrations.feature
Labels: area:test, area:ci, backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2831 [automation] update elastic stack version for testing 7.17.6-9675035b
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2837 [automation] update elastic stack version for testing 8.3.3-5fe7d8b1
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2835 [automation] update elastic stack version for testing 7.17.6-964edfea
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2836 [automation] update elastic stack version for testing 8.4.0-d058e92f
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2838 docs: simplify docs
  .ci/README.md
  .ci/ansible/tasks/setup_test_script.yml
  .ci/ansible/tasks/setup_test_script_windows.yml
  QUICKSTART.md
  README.md
  cli/README.md
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  e2e/README.md
  e2e/_suites/fleet/README.md
  e2e/_suites/kubernetes-autodiscover/README.md
  e2e/regression-testing.gif
  e2e/tooling.md
Labels: documentation, Team:Automation, area:test, area:ci, area:documentation, backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2842 chore: deprecate the usage of BEATS_LOCAL_PATH
  .ci/README.md
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
  internal/deploy/docker.go
  pkg/downloads/versions.go
  pkg/downloads/versions_test.go
Labels: Team:Automation, area:test, backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2853 [automation] update elastic stack version for testing 7.17.6-3f4b9bc6
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2850 chore: decouple responsibilities for fleet test suite code
  .pre-commit-config.yaml
  e2e/_suites/fleet/api_keys.go
  e2e/_suites/fleet/elastic_agent_checks.go
  e2e/_suites/fleet/elastic_agent_deploy.go
  e2e/_suites/fleet/elastic_agent_enroll.go
  e2e/_suites/fleet/endpoint.go
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/fleet_test.go
  e2e/_suites/fleet/ingest_manager_test.go
  e2e/_suites/fleet/integrations.go
  e2e/_suites/fleet/preconfigured_policies.go
  e2e/_suites/fleet/processes.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/fleet/system_integration.go
  e2e/_suites/fleet/upgrades.go
  e2e/_suites/helm/helm_charts_test.go
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
  e2e/templates/suite_test.go.tmpl
  internal/process/processes.go
Labels: Team:Automation, area:test, backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2867 [automation] update elastic stack version for testing 8.3.3-8631d33c
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2866 [automation] update elastic stack version for testing 8.4.0-60171339
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2871 [automation] update elastic stack version for testing 7.17.6-b64de485
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2869 [automation] update elastic stack version for testing 8.3.3-326db639
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2858 chore: simplify process action package
  internal/action/base.go
  internal/action/process.go
  internal/process/processes.go
Labels: backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2872 chore: bring back permission-change scenarios
  .ci/.e2e-tests-beats.yaml
  .ci/.e2e-tests-daily.yaml
  .ci/.e2e-tests-for-elastic-agent.yaml
  .ci/.e2e-tests.yaml
  e2e/_suites/fleet/api_keys.go
  e2e/_suites/fleet/elastic_agent_checks.go
  e2e/_suites/fleet/elastic_agent_enroll.go
  e2e/_suites/fleet/endpoint.go
  e2e/_suites/fleet/features/endpoint_integration.feature
  e2e/_suites/fleet/features/permission_output_change.feature
  e2e/_suites/fleet/fleet_test.go
  e2e/_suites/fleet/preconfigured_policies.go
  e2e/_suites/fleet/processes.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/fleet/system_integration.go
  e2e/_suites/fleet/upgrades.go
  internal/deploy/base.go
  internal/deploy/docker.go
  internal/deploy/docker_client.go
  internal/deploy/elastic_package.go
  internal/deploy/kubernetes.go
  internal/deploy/remote.go
  internal/io/io_test.go
Labels: Team:Automation, area:test, area:ci, backport-v8.3.0, backport-v8.2.0, backport-v7.17.0
