Repository elastic/e2e-testing, pull requests merged in 2022-06, with the labels that each got.

#2588 [automation] update elastic stack version for testing 7.17.5-7c990f83
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2587 [automation] update elastic stack version for testing 8.2.3-e78add13
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2563 chore: bump maintenance versions in mergify
  .mergify.yml
Labels: Team:Automation, backport-skip

#2593 [automation] update elastic stack version for testing 8.2.3-656a5d89
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2594 [automation] update elastic stack version for testing 7.17.5-a303ce60
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2590 fix: agent directories must belong to root
  internal/deploy/base.go
  internal/installer/base.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_docker.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/installer/elasticagent_tar_macos.go
  internal/installer/elasticagent_zip.go
Labels: Team:Automation, backport-v8.3.0

#2591 [automation] update elastic stack version for testing 8.4.0-df27a645
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2596 [automation] update elastic stack version for testing 8.2.3-f986a1ff
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2598 [automation] update elastic stack version for testing 7.17.5-f01fee6a
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2599 [automation] update elastic stack version for testing 8.3.0-378ebcca
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2597 [automation] update elastic stack version for testing 8.4.0-3525aaf7
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2552 Add test scenario for elastic agent tags
  .ci/README.md
  .gitignore
  e2e/_suites/fleet/features/fleet_mode.feature
  e2e/_suites/fleet/fleet.go
  internal/deploy/base.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_docker.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/installer/elasticagent_tar_macos.go
  internal/installer/elasticagent_zip.go
Labels: Team:Elastic-Agent-Control-Plane, v8.3.0, backport-v8.3.0

#2589 docs: document AWS requirements
  .ci/README.md
Labels: Team:Automation, area:documentation, backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2614 [automation] update elastic stack version for testing 8.2.3-def79f93
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2612 [automation] update elastic stack version for testing 7.17.5-572a2baf
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2613 [automation] update elastic stack version for testing 8.4.0-42ce0eef
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2611 [automation] update elastic stack version for testing 8.3.0-9596ee28
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2616 fix: retire 8.1 snapshot from upgrades
  e2e/_suites/fleet/features/upgrade_agent.feature
Labels: Team:Automation, backport-v8.3.0

#2620 [automation] update elastic stack version for testing 7.17.5-1c762894
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2603 Add support for Debian 11 and Ubuntu 22.04 platforms
  .ci/.e2e-platforms.yaml
  .ci/.e2e-tests-beats.yaml
  .ci/.e2e-tests-daily.yaml
  .ci/.e2e-tests-for-elastic-agent.yaml
  .ci/.e2e-tests.yaml
Labels: area:ci, Team:Elastic-Agent-Control-Plane, backport-skip, v8.4.0

#2622 [automation] update elastic stack version for testing 8.2.3-7def4c60
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2624 [automation] update elastic stack version for testing 7.17.5-dae6f87e
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2629 [automation] update elastic stack version for testing 8.2.3-a46e98e9
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2634 [automation] update elastic stack version for testing 8.2.3-4b95b897
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2637 chore: simplify extracting info from the supported platforms
  .ci/Makefile
  .ci/README.md
  .ci/scripts/yq.sh
  .gitignore
Labels: Team:Automation, backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2641 [automation] update elastic stack version for testing 8.2.3-b55b20b5
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2642 [automation] update elastic stack version for testing 8.3.0-e4e76686
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2647 Remove aws instance reaper Jenkins job
  .ci/aws-instances-reaper.groovy
  .ci/jobs/aws-instances-reaper.yml
Labels: area:ci, backport-skip

#2651 [automation] update elastic stack version for testing 8.3.0-fe62331f
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2650 [automation] update elastic stack version for testing 8.2.4-d8d37990
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2653 [automation] update elastic stack version for testing 8.2.4-4cc4fbfd
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2655 [automation] update elastic stack version for testing 8.2.4-01ccaf06
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2660 chore: increase build timeout to 2h
  .ci/Jenkinsfile
  .ci/e2eTestingFleetDaily.groovy
  .ci/e2eTestingHelmDaily.groovy
  .ci/e2eTestingK8SAutodiscoveryDaily.groovy
Labels: Team:Automation, area:ci, backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2661 chore(jjbb): increase build timeout to 2h
  .ci/jobs/e2e-testing-fleet-daily-mbp.yml
  .ci/jobs/e2e-testing-helm-daily-mbp.yml
  .ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml
  .ci/jobs/e2e-testing-mbp.yml
  .ci/schedule-daily.groovy
Labels: Team:Automation, area:ci, backport-skip

#2667 [automation] update elastic stack version for testing 8.2.4-698e06ec
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2671 [automation] update elastic stack version for testing 8.2.4-b657c8f5
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2626 Use Orka ephemeral workers to run the fleet testing
  .ci/bump-stack-version.sh
  .ci/e2eTestingMacosDaily.groovy
  .ci/jobs/e2e-testing-macos-mbp.yml
  .ci/schedule-daily.groovy
  .ci/scripts/deployment.sh
  .gitignore
  internal/elasticsearch/client.go
  internal/installer/elasticagent_tar_macos.go
  internal/kibana/client.go
Labels: backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2680 [automation] update elastic stack version for testing 8.2.4-589bdf37
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2679 [automation] update elastic stack version for testing 8.3.0-e0057e17
  .ci/Jenkinsfile
  .ci/e2eTestingMacosDaily.groovy
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2684 ci: support MacOS12
  .ci/e2eTestingMacosDaily.groovy
Labels: backport-v8.3.0, backport-v7.17.0

#2692 Add error checks to string typecast
  pkg/downloads/releases.go
Labels: bug, Team:Elastic-Agent-Data-Plane, backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2706 ci: notify test failures for MacOS nightly builds
  .ci/e2eTestingMacosDaily.groovy
Labels: backport-v8.3.0, backport-v7.17.0

#2700 [automation] update elastic stack version for testing 8.3.0-fdf97a2e
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2727 pkg/downloads: make sure nil resolvers are interpretted correctly
  pkg/downloads/releases.go
  pkg/downloads/versions.go
Labels: bug, backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2731 fix: update fleet mode tags
  .ci/.e2e-tests-beats.yaml
Labels: bug, backport-skip

#2717 ci: fix null for shell_type by throwing an error
  .ci/Jenkinsfile
Labels: backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2732 chore: log github checks variables
  pkg/downloads/versions.go
Labels: bug, backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2721 [automation] update elastic stack version for testing 7.17.5-b5794350
  .ci/Jenkinsfile
  .ci/e2eTestingMacosDaily.groovy
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2742 [automation] update elastic stack version for testing 8.3.1-b95de5e6
  .ci/Jenkinsfile
  .ci/e2eTestingMacosDaily.groovy
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2743 fix: read Git variables
  .ci/Jenkinsfile
  internal/common/defaults.go
  pkg/downloads/versions.go
Labels: bug, Team:Automation, area:test, area:ci, backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2749 fix space in the configuration file
  .ci/.e2e-tests-beats.yaml
  .ci/Jenkinsfile
Labels: bug, backport-skip
