Repository elastic/e2e-testing, pull requests merged in 2022-05, with the labels that each got.

#2455 [automation] update elastic stack version for testing 8.2.0-e7ad9ef0
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2456 [automation] update elastic stack version for testing 8.1.4-76569f3d
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2458 [automation] update elastic stack version for testing 7.17.4-ed667030
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2465 [automation] update elastic stack version for testing 8.2.0-56396fd0
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2464 [automation] update elastic stack version for testing 8.3.0-0b6ea9f2
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2466 [automation] update elastic stack version for testing 7.17.4-9ca33e9a
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2463 [automation] update elastic stack version for testing 8.1.4-1cdc80b6
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2469 [automation] update elastic stack version for testing 8.3.0-7f585873
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2471 [automation] update elastic stack version for testing 7.17.4-cd92752d
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2470 [automation] update elastic stack version for testing 8.1.4-86899ed7
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2472 chore: bump stale agent for 7.17
  .ci/Jenkinsfile
  internal/common/defaults.go
Labels: Team:Automation, area:test, backport-skip

#2475 [automation] update elastic stack version for testing 8.1.4-37d447ec
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2474 [automation] update elastic stack version for testing 8.3.0-a1c5cfff
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2454 docs: refactor docs to enable the local development
  .ci/.e2e-tests-for-elastic-agent.yaml
  .ci/.e2e-tests.yaml
  .ci/Jenkinsfile
  .ci/Makefile
  .ci/README.md
  .ci/ansible/playbook.yml
  .ci/ansible/tasks/runners.yml
  .ci/ansible/tasks/setup_test_script.yml
  .gitignore
  e2e/TROUBLESHOOTING.md
  e2e/_suites/fleet/README.md
  e2e/_suites/fleet/fleet.go
Labels: Team:Automation, area:test, area:ci, area:documentation, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#2476 [automation] update elastic stack version for testing 7.17.4-c570579f
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2483 [automation] update elastic stack version for testing 8.1.4-6c818705
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2484 [automation] update elastic stack version for testing 8.3.0-6ba9f710
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2485 [automation] update elastic stack version for testing 7.17.4-2fe5353f
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2486 chore: wait for the stack while provisioning
  .ci/ansible/playbook.yml
Labels: Team:Automation, area:ci, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#2477 chore: reduce AWS instances size
  .ci/.e2e-platforms.yaml
  .ci/Makefile
Labels: Team:Automation, area:ci, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#2494 [automation] update elastic stack version for testing 8.3.0-5c1ff35f
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2495 [automation] update elastic stack version for testing 7.17.4-1ffd290e
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2482 chore: skip system-integration scenarios for Beats
  .ci/.e2e-tests-beats.yaml
Labels: Team:Automation, area:ci, requested-by:Obs-DC, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#2496 chore: refactor cucumber tags
  .ci/.e2e-tests-for-elastic-agent.yaml
  .ci/.e2e-tests.yaml
  .ci/Makefile
  .ci/README.md
  e2e/Makefile
  e2e/README.md
  e2e/TROUBLESHOOTING.md
  e2e/_suites/fleet/features/apm_integration.feature
  e2e/_suites/fleet/features/endpoint_integration.feature
  e2e/_suites/fleet/features/fleet_mode.feature
  e2e/_suites/fleet/features/integrations.feature
  e2e/_suites/fleet/features/linux_integration.feature
  e2e/_suites/fleet/features/permission_output_change.feature
  e2e/_suites/fleet/features/preconfigured_policies.feature
  e2e/_suites/fleet/features/running_on_top_of_beats.feature
  e2e/_suites/fleet/features/stand_alone_mode.feature
  e2e/_suites/fleet/features/system_integration.feature
Labels: Team:Automation, area:test, area:ci, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#2505 [automation] update elastic stack version for testing 8.3.0-d380914f
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2506 [automation] update elastic stack version for testing 8.2.1-d6d75d75
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2507 [automation] update elastic stack version for testing 7.17.4-37e626ca
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2501 avoid aliases if no major.minor format
  internal/common/defaults.go
Labels: backport-v8.3.0, backport-v8.2.0, backport-v7.17.0

#2513 [automation] update elastic stack version for testing 8.3.0-53513548
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2514 [automation] update elastic stack version for testing 8.2.1-2eb01953
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2518 [automation] update elastic stack version for testing 8.2.1-91d7a53f
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2519 [automation] update elastic stack version for testing 8.3.0-8ee1196f
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2520 [automation] update elastic stack version for testing 7.17.4-6a00b8d7
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2522 [automation] update elastic stack version for testing 8.3.0-b85385ff
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2523 [automation] update elastic stack version for testing 7.17.4-153c53bf
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2354 fix: install stale agent properly
  .ci/.e2e-tests-for-elastic-agent.yaml
  .ci/.e2e-tests.yaml
  .ci/Jenkinsfile
  e2e/README.md
  e2e/_suites/fleet/features/fleet_mode.feature
  e2e/_suites/fleet/features/upgrade_agent.feature
  e2e/_suites/fleet/fleet.go
  go.mod
  internal/common/defaults.go
  internal/curl/curl.go
  internal/deploy/base.go
  internal/deploy/base_test.go
  internal/installer/base.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_docker.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/installer/elasticagent_tar_macos.go
  internal/installer/elasticagent_zip.go
  internal/kibana/agents.go
  internal/kibana/client.go
  pkg/downloads/releases.go
  pkg/downloads/versions.go
  pkg/downloads/versions_test.go
Labels: bug, Team:Automation, area:test, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#2529 [automation] update elastic stack version for testing 8.2.1-3d12787c
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2528 [automation] update elastic stack version for testing 8.3.0-19aba912
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2530 [automation] update elastic stack version for testing 7.17.4-191b5600
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2535 [automation] update elastic stack version for testing 8.2.1-736d131e
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2537 [automation] update elastic stack version for testing 8.3.0-4149272f
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2536 [automation] update elastic stack version for testing 7.17.4-16fc7c23
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2539 [automation] update elastic stack version for testing 8.3.0-e4aa1f83
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2538 [automation] update elastic stack version for testing 8.2.1-8d9ffca9
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2540 [automation] update elastic stack version for testing 7.17.4-3585da41
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2545 [automation] update elastic stack version for testing 7.17.4-16f62393
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2548 [automation] update elastic stack version for testing 7.17.4-60cd01b1
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2564 chore: do not run apm-server helm chart scenarios for Beats
  .ci/.e2e-tests-beats.yaml
Labels: Team:Automation, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#2569 fix: use fixed, valid version for protobuffers
  .ci/ansible/requirements.txt
Labels: backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0

#2562 chore: bump kubernetes versions
  .ci/Jenkinsfile
  .ci/ansible/tasks/setup_test_script.yml
  .ci/scripts/install-helm-test-dependencies.sh
  .ci/scripts/install-kubernetes-autodiscover-test-dependencies.sh
  .ci/scripts/install-test-dependencies.sh
  cli/config/kubernetes/README.md
  e2e/_suites/fleet/features/backend_processes.feature
  e2e/_suites/helm/README.md
  e2e/_suites/helm/helm_charts_test.go
  e2e/_suites/kubernetes-autodiscover/README.md
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
  internal/kubectl/kubectl.go
Labels: bug, Team:Automation, backport-v8.3.0, backport-v8.1.0, backport-v8.2.0, backport-v7.17.0
