Repository elastic/e2e-testing, pull requests merged in 2022-03, with the labels that each got.

#2189 [automation] update elastic stack version for testing 7.17.1-bf42f386
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2188 [automation] update elastic stack version for testing 8.2.0-bdf2ad74
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2130 chore: use trace level in logs
  .ci/Jenkinsfile
  .ci/ansible/tasks/setup_test_script.yml
Labels: backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#2193 [automation] update elastic stack version for testing 8.2.0-43df679f
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2195 [automation] update elastic stack version for testing 7.17.2-3e73f87b
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2198 fix: bump stale agent
  .ci/Jenkinsfile
  internal/common/defaults.go
Labels: Team:Automation, backport-skip

#2200 [automation] update elastic stack version for testing 8.2.0-fdde08ec
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2201 [automation] update elastic stack version for testing 7.17.2-e8098595
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2206 [automation] update elastic stack version for testing 8.2.0-190af159
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2207 [automation] update elastic stack version for testing 8.0.2-ae36dda7
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2208 chore: support for Oracle Linux 8
  .ci/.e2e-tests-for-elastic-agent.yaml
  .ci/.e2e-tests.yaml
  .ci/ansible/tasks/install_deps.yml
  .ci/ansible/tasks/runners.yml
Labels: Team:Automation, area:test, size:S, area:ci, Team:Elastic-Agent-Control-Plane, backport-skip

#2210 [automation] update elastic stack version for testing 8.0.2-901e2b50
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2209 [automation] update elastic stack version for testing 8.2.0-a12f7069
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2211 [automation] update elastic stack version for testing 8.1.0-52a8d1d4
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2212 ci: provision e2-small workers
  .ci/Jenkinsfile
Labels: backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#2213 chore: define provider for each test suite
  .ci/.e2e-platforms.yaml
  .ci/.e2e-tests-for-elastic-agent.yaml
  .ci/.e2e-tests.yaml
  .ci/Jenkinsfile
  .ci/README.md
  .ci/ansible/tasks/setup_test_script.yml
  README.md
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/stand-alone.go
  internal/kibana/fleet.go
  internal/kibana/policies.go
Labels: backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#2220 fix: wrong link
  README.md
Labels: bug, documentation, backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#2225 [automation] update elastic stack version for testing 8.2.0-63265ec9
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2224 [automation] update elastic stack version for testing 8.1.1-b9a6c108
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2226 [automation] update elastic stack version for testing 7.17.2-c18736fc
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2228 [automation] update elastic stack version for testing 8.2.0-d02c907a
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2227 [automation] update elastic stack version for testing 8.1.1-da392dcd
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2203 Separate ES workload from Agent spec and make it req for the scenarios
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
  e2e/_suites/kubernetes-autodiscover/features/elastic_agent_standalone.feature
  e2e/_suites/kubernetes-autodiscover/testdata/templates/elastic-agent.yml.tmpl
  e2e/_suites/kubernetes-autodiscover/testdata/templates/elasticsearch.yml.tmpl
Labels: backport-skip

#2234 [automation] update elastic stack version for testing 8.2.0-fee3b8d2
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2237 fix: add end-of-file line in templates
  e2e/_suites/kubernetes-autodiscover/testdata/templates/elastic-agent.yml.tmpl
  e2e/_suites/kubernetes-autodiscover/testdata/templates/elasticsearch.yml.tmpl
Labels: backport-skip

#2235 [automation] update elastic stack version for testing 7.17.2-8be09371
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2236 [automation] update elastic stack version for testing 8.1.1-2d188131
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2240 [automation] update elastic stack version for testing 8.2.0-9bac538c
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2238 [automation] update elastic stack version for testing 7.17.2-2208f979
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2239 [automation] update elastic stack version for testing 8.1.1-31faf00b
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2242 [automation] update elastic stack version for testing 8.2.0-ff67d7b8
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2243 [automation] update elastic stack version for testing 7.17.2-8f7db3a8
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2244 [automation] update elastic stack version for testing 8.1.1-9bb65a23
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2246 fix: never process elasticsearch CI artifacts
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
Labels: bug, Team:Automation, backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#2250 [automation] update elastic stack version for testing 8.2.0-82b803a1
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2251 [automation] update elastic stack version for testing 8.1.1-da22c151
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2255 [automation] update elastic stack version for testing 7.17.2-3b3b663d
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2253 [automation] update elastic stack version for testing 8.1.1-0d572bb7
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2254 [automation] update elastic stack version for testing 8.2.0-5cc993c1
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2261 [automation] update elastic stack version for testing 7.17.2-81597e21
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2260 [automation] update elastic stack version for testing 8.1.1-c72e1d1e
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2264 [automation] update elastic stack version for testing 7.17.2-70a05b08
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2265 [automation] update elastic stack version for testing 8.2.0-4509f321
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2267 [automation] update elastic stack version for testing 8.1.2-2393b0c1
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2268 [automation] update elastic stack version for testing 7.17.2-1941719d
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2270 [automation] update elastic stack version for testing 8.2.0-dcff22d7
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2269 [automation] update elastic stack version for testing 8.1.2-5d446358
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2271 [automation] update elastic stack version for testing 8.1.2-d0bc828f
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2272 [automation] update elastic stack version for testing 7.17.2-cf7cf1eb
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2273 chore: include suite, platform and tags in test reports name
  .ci/Jenkinsfile
  .ci/ansible/tasks/setup_test_script.yml
  .ci/scripts/functional-test.sh
Labels: backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#2282 [automation] update elastic stack version for testing 8.1.2-e94d7716
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2283 [automation] update elastic stack version for testing 7.17.2-99f889e2
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2284 fix: always quote variables in shell scripts
  .ci/Jenkinsfile
  .ci/ansible/tasks/setup_test_script.yml
  .ci/scripts/functional-test.sh
  .ci/scripts/generate-cucumber-reports.sh
  e2e/_suites/fleet/features/agent_endpoint_integration.feature
  e2e/_suites/fleet/features/fleet_mode_agent.feature
  e2e/commons-test.mk
Labels: bug, Team:Automation, priority:blocker, area:ci, impact:critical, backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#2292 [automation] update elastic stack version for testing 7.17.2-a218ac35
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2291 [automation] update elastic stack version for testing 8.1.2-52f4e5e3
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2294 fix: increase scheduled build timeouts to 90 min
  .ci/e2eTestingFleetDaily.groovy
  .ci/e2eTestingHelmDaily.groovy
  .ci/e2eTestingK8SAutodiscoveryDaily.groovy
Labels: Team:Automation, backport-v8.0.0, backport-v8.1.0, backport-v7.17.0
