Repository elastic/e2e-testing, pull requests merged in 2022-11, with the labels that each got.

#3183 [automation] update elastic stack version for testing 8.4.4-55734bd7
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3177 Adjust README
  .ci/README.md
Labels: documentation, Team:Elastic-Agent, backport-skip

#3184 [automation] update elastic stack version for testing 8.6.0-4765d2b0
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3181 fix ineffassign for the version when using tar on MacOS
  internal/installer/elasticagent_tar_macos.go
Labels: bug, backport-v7.17.0, backport-v8.5.0

#3188 [automation] update elastic stack version for testing 8.4.4-dcd4a95f
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3187 [automation] update elastic stack version for testing 8.6.0-8a615646
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3191 [automation] update elastic stack version for testing 8.5.1-7fd6ffae
  .ci/Jenkinsfile
  .ci/e2eTestingMacosDaily.groovy
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3192 [automation] update elastic stack version for testing 8.6.0-3f5f98b7
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3190 kibana: fail on error and improve log messages
  internal/kibana/url_prefixes.go
Labels: backport-skip

#3196 [automation] update elastic stack version for testing 8.5.1-2ceb7fad
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3138 actions: run unit-tests and linting in GH actions
  .ci/Jenkinsfile
  .github/workflows/golangci-lint.yml
  .github/workflows/junit-test-reporter.yml
  .github/workflows/pull-request.yml
  .go-version
  .pre-commit-config.yaml
Labels: backport-v7.17.0, backport-v8.5.0

#3167 Update references of epr-staging to production
  .ci/ansible/elastic-stack.yml
  internal/config/compose/profiles/fleet/default/kibana.config.yml
  internal/config/compose/profiles/fleet/preconfigured-policies/kibana.config.yml
  internal/config/kubernetes/base/package-registry/deployment.yaml
Labels: backport-skip

#3203 [automation] update elastic stack version for testing 8.6.0-da453972
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3204 [automation] update elastic stack version for testing 8.5.1-2041424b
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3205 [automation] update elastic stack version for testing 7.17.8-a281a566
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3208 [automation] update elastic stack version for testing 8.5.1-6bdef2c7
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3206 [automation] update elastic stack version for testing 8.6.0-c9d1a5e9
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3211 [automation] update elastic stack version for testing 8.5.1-1f91140d
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3213 [automation] update elastic stack version for testing 8.5.1-d7343c55
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3212 [automation] update elastic stack version for testing 7.17.8-8be7042c
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3216 [automation] update elastic stack version for testing 8.5.1-49e04c16
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3219 backport: Add 8.6 branch
  .mergify.yml
Labels: Team:Automation, backport-skip, release

#3223 [automation] update elastic stack version for testing 8.5.2-733d317b
  .ci/Jenkinsfile
  .ci/e2eTestingMacosDaily.groovy
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3224 [automation] update elastic stack version for testing 7.17.8-ca244ec8
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3228 [automation] update elastic stack version for testing 8.5.2-13a22054
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3232 [automation] update elastic stack version for testing 8.5.2-c2e5a3f4
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3234 [automation] update elastic stack version for testing 8.5.2-98bdbc90
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3238 [automation] update elastic stack version for testing 8.5.3-760caed9
  .ci/Jenkinsfile
  .ci/e2eTestingMacosDaily.groovy
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3242 [automation] update elastic stack version for testing 8.5.3-c0681f01
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3245 [automation] update elastic stack version for testing 8.5.3-a0b682b9
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3246 [automation] update elastic stack version for testing 8.5.3-770e9287
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3251 [automation] update elastic stack version for testing 8.5.3-a46b25ec
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip
