Repository elastic/e2e-testing, pull requests merged in 2022-02, with the labels that each got.

#2084 chore: remove slack notifications to infra-release-notify
  .ci/e2eTestingHelmDaily.groovy
Labels: helm, backport-v7.16.0, backport-v8.0.0, backport-v7.17.0

#2107 fix: update APT cache for both Debian and Ubuntu
  .ci/ansible/playbook.yml
  .ci/ansible/tasks/install_deps.yml
Labels: backport-v7.16.0, backport-v8.0.0, backport-v7.17.0

#2112 Update github-ssh-keys
  .ci/ansible/github-ssh-keys
Labels: backport-skip

#2104 [automation] update elastic stack version for testing 8.2.0-5d69c4c3
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2105 [automation] update elastic stack version for testing 7.17.1-48ecd1f2
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2106 [automation] update elastic stack version for testing 7.16.4-047be5da
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2111 chore: use preconfigured policy for fleet-server's default policy
  cli/config/compose/profiles/fleet/default/kibana.config.yml
  cli/config/compose/profiles/fleet/preconfigured-policies/kibana.config.yml
  e2e/_suites/fleet/fleet.go
  internal/kibana/policies.go
Labels: Team:Automation, Team:Fleet, backport-v8.0.0

#2121 fix: use valid version for 8.0
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
Labels: bug, backport-skip

#2119 fix: use valid version for fleet-server-7.16
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
Labels: bug, backport-skip

#2123 chore: bump version for services
  .ci/bump-stack-version.sh
Labels: backport-v7.16.0, backport-v8.0.0, backport-v7.17.0

#2127 fix: add missing backports selectively
  .ci/Jenkinsfile
  .ci/ansible/playbook.yml
  .ci/ansible/tasks/copy_test_files.yml
  .ci/ansible/tasks/install_deps.yml
  .ci/ansible/tasks/runners.yml
  .ci/ansible/tasks/setup_test_script.yml
  e2e/_suites/fleet/fleet.go
  internal/kibana/policies.go
Labels: Team:Automation, area:ci, backport-skip

#2128 chore: bump Go version
  .ci/ansible/playbook.yml
  e2e/_suites/fleet/fleet.go
  internal/kibana/policies.go
Labels: Team:Automation, area:ci, backport-skip

#2129 fix: right version for 8.0
  cli/config/compose/services/elastic-agent/docker-compose.yml
Labels: Team:Automation, area:ci, backport-skip

#2133 Revert "[8.0](backport #2111) chore: use preconfigured policy for fleet-server's default policy (#2116)"
  cli/config/compose/profiles/fleet/default/kibana.config.yml
  cli/config/compose/profiles/fleet/preconfigured-policies/kibana.config.yml
  e2e/_suites/fleet/fleet.go
  internal/kibana/policies.go
Labels: backport-skip

#2131 fix: sync versions with stack
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
Labels: skip_backport, backport-skip

#2138 ci: increase log rotation
  .ci/Jenkinsfile
Labels: backport-skip

#2139 chore: increase build timeout to 90 minutes
  .ci/Jenkinsfile
Labels: backport-skip

#2141 Install jq tool in elastic-agent container to parse ES output
  e2e/_suites/kubernetes-autodiscover/testdata/templates/elastic-agent.yml.tmpl
Labels: backport-v7.16.0, backport-v8.0.0, backport-v7.17.0

#2146 [automation] update elastic stack version for testing 7.17.1-d1501547
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2148 [automation] update elastic stack version for testing 8.1.0-c6173806
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2150 [automation] update elastic stack version for testing 8.2.0-74785f8b
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2151 [automation] update elastic stack version for testing 7.17.1-9bbee73a
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2153 [automation] update elastic stack version for testing 7.17.1-598c7994
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2154 [automation] update elastic stack version for testing 8.2.0-2e8f5958
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2155 Add ph to the e2e github-ssh-keys
  .ci/ansible/github-ssh-keys
Labels: backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#2158 jjbb: enable 8.1 and disable 7.16
  .ci/jobs/e2e-testing-fleet-daily-mbp.yml
  .ci/jobs/e2e-testing-helm-daily-mbp.yml
  .ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml
  .ci/jobs/e2e-testing-mbp.yml
Labels: backport-skip

#2163 chore: decouple ansible install from execution
  .ci/Jenkinsfile
Labels: Team:Automation, priority:medium, size:S, triaged, backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#2160 [automation] update elastic stack version for testing 8.2.0-ba537863
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2159 jjbb: daily job with branch aliases
  .backportrc.json
  .ci/e2eTestingFleetDaily.groovy
  .ci/e2eTestingHelmDaily.groovy
  .ci/e2eTestingK8SAutodiscoveryDaily.groovy
  .ci/jobs/e2e-testing-fleet-daily-mbp.yml
  .ci/jobs/e2e-testing-helm-daily-mbp.yml
  .ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml
  .ci/jobs/e2e-testing-schedule-daily.yml
  .ci/schedule-daily.groovy
  .mergify.yml
Labels: backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#2173 [automation] update elastic stack version for testing 8.2.0-313c1e34
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2174 [automation] update elastic stack version for testing 8.1.0-03fdea33
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2176 [automation] update elastic stack version for testing 8.2.0-c2195520
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2179 [automation] update elastic stack version for testing 8.2.0-4a677e18
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2178 [automation] update elastic stack version for testing 7.17.1-952e96f1
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2180 [automation] update elastic stack version for testing 8.1.0-f6199768
  .ci/Jenkinsfile
  .stack-version
  cli/config/compose/profiles/fleet/docker-compose.yml
  cli/config/compose/profiles/metricbeat/docker-compose.yml
  cli/config/compose/services/elastic-agent/cloud/docker-compose.yml
  cli/config/compose/services/elastic-agent/docker-compose.yml
  cli/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  cli/config/compose/services/elasticsearch/docker-compose.yml
  cli/config/compose/services/kibana/docker-compose.yml
  cli/config/compose/services/metricbeat/docker-compose.yml
  cli/config/kubernetes/base/elasticsearch/deployment.yaml
  cli/config/kubernetes/base/fleet-server/deployment.yaml
  cli/config/kubernetes/base/kibana/deployment.yaml
  internal/common/defaults.go
Labels: automation, dependency, backport-skip

#2172 feat: support downloading project artifacts for the new bucket layout
  .ci/Jenkinsfile
  .ci/ansible/tasks/setup_test_script.yml
  .ci/bump-stack-version.sh
  .ci/scripts/functional-test.sh
  e2e/README.md
  e2e/_suites/fleet/README.md
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest_manager_test.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/kubernetes-autodiscover/README.md
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
  internal/common/defaults.go
  internal/deploy/docker.go
  internal/deploy/docker_test.go
  internal/deploy/elastic_package.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_docker.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/installer/elasticagent_tar_macos.go
  internal/installer/elasticagent_zip.go
  pkg/downloads/buckets.go
  pkg/downloads/buckets_test.go
  pkg/downloads/versions.go
  pkg/downloads/versions_test.go
Labels: Team:Automation, area:test, size:S, backport-v8.0.0, backport-v8.1.0, backport-v7.17.0

#2186 chore: increase build timeout to 90 minutes (#2139) backport for 7.17
  .ci/Jenkinsfile
Labels: backport

#2185 chore: increase build timeout to 90 minutes (#2139) backport for 8.0
  .ci/Jenkinsfile
Labels: backport

#2187 chore: 7.17 backports
  .ci/Jenkinsfile
  .ci/ansible/tasks/setup_test_script.yml
  .ci/bump-stack-version.sh
  .ci/scripts/functional-test.sh
  Makefile
  e2e/README.md
  e2e/_suites/fleet/README.md
  e2e/_suites/fleet/fleet.go
  e2e/_suites/fleet/ingest_manager_test.go
  e2e/_suites/fleet/stand-alone.go
  e2e/_suites/kubernetes-autodiscover/README.md
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
  internal/common/defaults.go
  internal/deploy/docker.go
  internal/deploy/docker_test.go
  internal/deploy/elastic_package.go
  internal/installer/elasticagent_deb.go
  internal/installer/elasticagent_docker.go
  internal/installer/elasticagent_rpm.go
  internal/installer/elasticagent_tar.go
  internal/installer/elasticagent_tar_macos.go
  internal/installer/elasticagent_zip.go
  internal/utils/utils.go
  internal/utils/utils_test.go
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-aarch64.rpm
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-amd64.deb
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-arm64.deb
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-amd64.docker.tar.gz
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-amd64.tar.gz
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-arm64.docker.tar.gz
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-arm64.tar.gz
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-linux-x86_64.tar.gz
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-BEATS_VERSION-x86_64.rpm
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-ubi8-BEATS_VERSION-linux-amd64.docker.tar.gz
  pkg/_testresources/beats/x-pack/elastic-agent/build/distributions/elastic-agent-ubi8-BEATS_VERSION-linux-arm64.docker.tar.gz
  pkg/_testresources/gcp/commits.json
  pkg/_testresources/gcp/nextPageParam.json
  pkg/_testresources/gcp/snapshots.json
  pkg/downloads/buckets.go
  pkg/downloads/buckets_test.go
  pkg/downloads/versions.go
  pkg/downloads/versions_test.go
Labels: backport-skip

#2184 chore: increase build timeout to 90 minutes (#2139) backport for 8.1
  .ci/Jenkinsfile
Labels: backport
