Repository elastic/e2e-testing, pull requests merged in 2022-08, with the labels that each got.

#2881 [automation] update elastic stack version for testing 7.17.6-74b6df3e
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2857 backport: Add 8.4 branch
  .backportrc.json
  .mergify.yml
Labels: Team:Automation, backport-skip

#2882 fix: poll for api key verification using backoff retry
  e2e/_suites/fleet/api_keys.go
Labels: backport-v8.3.0, backport-v7.17.0, backport-v8.4.0

#2880 [automation] update elastic stack version for testing 8.4.0-d88c8a44
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2879 chore: bring back stand-alone agent
  .ci/.e2e-tests-daily.yaml
  .ci/.e2e-tests-for-elastic-agent.yaml
  .ci/.e2e-tests.yaml
  .ci/ansible/playbook.yml
  .ci/ansible/tasks/install_deps.yml
  e2e/_suites/fleet/elastic_agent_deploy.go
  e2e/_suites/fleet/elastic_agent_enroll.go
  e2e/_suites/fleet/features/stand_alone_mode.feature
  e2e/_suites/fleet/stand-alone.go
Labels: Team:Automation, backport-v8.3.0, backport-v7.17.0, backport-v8.4.0

#2888 docs: add Python version
  .ci/README.md
Labels: Team:Automation, backport-v8.3.0, backport-v7.17.0, backport-v8.4.0

#2889 fix: add resiliency when consolidating the cucumber reports
  .ci/Jenkinsfile
Labels: Team:Automation, backport-v8.3.0, backport-v7.17.0, backport-v8.4.0

#2884 chore: use a more descriptive name for debian 10
  .ci/.e2e-platforms.yaml
  .ci/.e2e-tests-beats.yaml
  .ci/.e2e-tests-daily.yaml
  .ci/.e2e-tests-for-elastic-agent.yaml
  .ci/.e2e-tests.yaml
  .ci/Makefile
  .ci/README.md
Labels: Team:Automation, backport-v7.17.0

#2900 [automation] update elastic stack version for testing 8.4.0-5954f776
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2901 [automation] update elastic stack version for testing 8.3.4-9c50d4cb
  .ci/Jenkinsfile
  .ci/e2eTestingMacosDaily.groovy
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2902 [automation] update elastic stack version for testing 8.5.0-7dbc10f8
  .ci/Jenkinsfile
  .ci/e2eTestingMacosDaily.groovy
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2904 [automation] update elastic stack version for testing 7.17.6-02b91d00
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2905 [automation] update elastic stack version for testing 8.3.4-a15c6beb
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2906 fix: retire 8.2-SNAPSHOT from upgrade tests
  e2e/_suites/fleet/features/upgrade_agent.feature
Labels: area:test, backport-skip

#2908 fix: retire 8.2-SNAPSHOT from upgrade tests
  e2e/_suites/fleet/features/upgrade_agent.feature
Labels: area:test, backport-skip

#2907 fix: retire 8.2-SNAPSHOT from upgrade tests
  e2e/_suites/fleet/features/upgrade_agent.feature
Labels: area:test, backport-skip

#2910 [automation] update elastic stack version for testing 8.3.4-ce266bfe
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2911 [automation] update elastic stack version for testing 7.17.6-308858b9
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2903 chore: poll the package policies to detect if package is in policy
  e2e/_suites/fleet/system_integration.go
  internal/kibana/integrations.go
Labels: Team:Automation, backport-v8.3.0, backport-v7.17.0, system-integration, backport-v8.4.0

#2912 [automation] update elastic stack version for testing 8.4.0-b5074ef3
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2918 [automation] update elastic stack version for testing 7.17.6-39f8da8e
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2917 [automation] update elastic stack version for testing 8.3.4-73c9af3c
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2919 [automation] update elastic stack version for testing 7.17.6-49d2f2df
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2924 [automation] update elastic stack version for testing 8.3.4-fd43be48
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2944 [automation] update elastic stack version for testing 7.17.6-202119fd
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2945 [automation] update elastic stack version for testing 7.17.6-091e6fb1
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2952 [automation] update elastic stack version for testing 7.17.6-b8ca5a33
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2953 [automation] update elastic stack version for testing 7.17.6-a9c53531
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#2977 ci: schedule builds for the feature-arch-v2 branch
  .ci/schedule-daily.groovy
Labels: backport-skip
