Repository elastic/e2e-testing, pull requests merged in 2022-10, with the labels that each got.

#3054 Only run Fleet mode and upgrade tests on Ubuntu 22
  .ci/.e2e-tests-daily.yaml
  .ci/.e2e-tests.yaml
Labels: backport-v8.4.0, backport-v8.5.0

#3029 backport: Add 8.5 branch
  .mergify.yml
Labels: Team:Automation, backport-skip

#3077 Turn off all tests but Fleet mode and upgrade for Beats and Agent pipelines
  .ci/.e2e-tests-beats.yaml
  .ci/.e2e-tests-for-elastic-agent.yaml
Labels: backport-v8.4.0, backport-v8.5.0

#3081 [automation] update elastic stack version for testing 8.6.0-0fca2953
  .ci/Jenkinsfile
  .ci/e2eTestingMacosDaily.groovy
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3092 [automation] update elastic stack version for testing 8.5.0-58624073
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3098 [automation] update elastic stack version for testing 8.4.4-ac374c4b
  .ci/Jenkinsfile
  .ci/e2eTestingMacosDaily.groovy
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3099 [automation] update elastic stack version for testing 7.17.7-f9849b81
  .ci/Jenkinsfile
  .ci/e2eTestingMacosDaily.groovy
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3097 [automation] update elastic stack version for testing 8.5.0-c52257ee
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3096 [automation] update elastic stack version for testing 8.6.0-d939cfde
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3105 [automation] update elastic stack version for testing 8.6.0-7c9f25a9
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3103 [automation] update elastic stack version for testing 8.4.4-17ce02d0
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3104 [automation] update elastic stack version for testing 7.17.7-3947c049
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3102 [automation] update elastic stack version for testing 8.5.0-7d416dc4
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3106 [automation] update elastic stack version for testing 8.6.0-c49fac70
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3108 [automation] update elastic stack version for testing 8.4.4-221d2ff4
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3107 [automation] update elastic stack version for testing 8.5.0-4f4df9f4
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3110 [automation] update elastic stack version for testing 8.5.0-09886b6e
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3111 [automation] update elastic stack version for testing 8.6.0-5a8d757d
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3115 [automation] update elastic stack version for testing 8.6.0-40086bc7
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3114 [automation] update elastic stack version for testing 8.5.0-fe2e6147
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3116 [automation] update elastic stack version for testing 8.4.4-1129f33b
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3117 [automation] update elastic stack version for testing 7.17.7-a44998d0
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3122 [automation] update elastic stack version for testing 8.6.0-233dc5d4
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3120 [automation] update elastic stack version for testing 8.5.0-976bca07
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3121 [automation] update elastic stack version for testing 8.4.4-fdf1902b
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3119 [automation] update elastic stack version for testing 7.17.7-40d7eba9
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3124 [automation] update elastic stack version for testing 8.5.0-f8c98e5d
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3125 [automation] update elastic stack version for testing 8.6.0-54a302f0
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3131 [automation] update elastic stack version for testing 8.4.4-93b2bfdf
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3130 [automation] update elastic stack version for testing 8.6.0-cae815eb
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3129 [automation] update elastic stack version for testing 8.5.0-7c74e950
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3133 [automation] update elastic stack version for testing 8.4.4-e97ba82f
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3134 [automation] update elastic stack version for testing 8.5.0-792499b4
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3135 [automation] update elastic stack version for testing 8.6.0-6545f2df
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3140 [automation] update elastic stack version for testing 8.6.0-055acc83
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3143 [automation] update elastic stack version for testing 8.4.4-51bbfe53
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3139 chore: fix linting
  e2e/_suites/helm/helm_charts_test.go
  internal/config/config.go
  internal/elasticsearch/client.go
  tools/tools.go
Labels: backport-v7.17.0, backport-v8.4.0, backport-v8.5.0

#3141 [automation] update elastic stack version for testing 8.5.0-7e528e3e
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3137 ci: reprovision worker if it's flaky
  .ci/Jenkinsfile
Labels: automation, Team:Automation, backport-v7.17.0, backport-v8.4.0, backport-v8.5.0

#3151 [automation] update elastic stack version for testing 8.6.0-baf193e8
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3154 [automation] update elastic stack version for testing 8.5.0-754ef325
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3153 [automation] update elastic stack version for testing 7.17.7-60386d02
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3156 [automation] update elastic stack version for testing 8.4.4-9b801d60
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3155 [automation] update elastic stack version for testing 8.6.0-22d60ec9
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3162 [automation] update elastic stack version for testing 8.4.4-46f2f222
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3161 [automation] update elastic stack version for testing 8.6.0-b8b35931
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3160 [automation] update elastic stack version for testing 8.5.0-d7b01592
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3163 [automation] update elastic stack version for testing 7.17.7-0a02d958
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3164 Add license file
  LICENSE.txt
  README.md
Labels: backport-skip

#3166 [automation] update elastic stack version for testing 8.4.4-1ee39d03
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3170 [automation] update elastic stack version for testing 8.4.4-d66e996a
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3171 [automation] update elastic stack version for testing 8.5.0-eb17cbd2
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3172 [automation] update elastic stack version for testing 8.6.0-a892f234
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3176 [automation] update elastic stack version for testing 8.4.4-6eb63640
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3175 [automation] update elastic stack version for testing 8.5.0-4028b295
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3173 [automation] update elastic stack version for testing 8.6.0-89d224d2
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3174 [automation] update elastic stack version for testing 7.17.8-d89bf16d
  .ci/Jenkinsfile
  .ci/e2eTestingMacosDaily.groovy
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3180 [automation] update elastic stack version for testing 8.4.4-f3b8851a
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3178 [automation] update elastic stack version for testing 8.5.0-f48cdca0
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3179 [automation] update elastic stack version for testing 8.6.0-949a38d2
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip
