Repository elastic/e2e-testing, pull requests merged in 2023-08, with the labels that each got.

#3596 Migrate k8s autodiscovery pipeline
  .ci/e2eTestingK8SAutodiscoveryDaily.groovy
  .ci/jobs/e2e-testing-k8s-autodiscovery-daily-mbp.yml
  .github/workflows/k8s-autodiscovery-test.yml
  .github/workflows/opentelemetry.yml
  e2e/_suites/kubernetes-autodiscover/autodiscover_test.go
Labels: backport-v7.17.0, backport-v8.8.0, backport-v8.9.0

#3605 Set fail-fast to false for k8s-autodiscovery-test
  .github/workflows/k8s-autodiscovery-test.yml
Labels: backport-skip

#3612 Update K8s and Kind version
  .ci/scripts/install-helm-test-dependencies.sh
  .ci/scripts/install-kubernetes-autodiscover-test-dependencies.sh
  .go-version
  e2e/_suites/kubernetes-autodiscover/README.md
  internal/config/kubernetes/README.md
Labels: backport-skip

#3622 Allow downloading artifacts from project specific locations
  internal/utils/utils.go
  pkg/downloads/releases.go
  pkg/downloads/releases_test.go
  pkg/downloads/versions.go
Labels: Team:Elastic-Agent, backport-skip
