Repository elastic/e2e-testing, pull requests merged in 2023-05, with the labels that each got.

#3483 [updatecli] update elastic stack version for testing 8.7.1-79685088
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3484 [updatecli] update elastic stack version for testing 8.8.0-1fcea9ba
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3485 [updatecli] update elastic stack version for testing 8.8.0-de6751d7
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3486 [updatecli] update elastic stack version for testing 8.9.0-a2c79020
  .ci/Jenkinsfile
  .ci/e2eTestingMacosDaily.groovy
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3488 [updatecli] update elastic stack version for testing 8.7.1-2ea32c14
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3491 [updatecli] update elastic stack version for testing 8.7.2-a5f8cdcb
  .ci/Jenkinsfile
  .ci/e2eTestingMacosDaily.groovy
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3492 [updatecli] update elastic stack version for testing 8.8.0-97faefbe
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3494 [updatecli] update elastic stack version for testing 8.8.0-8d0a4918
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3495 [updatecli] update elastic stack version for testing 8.9.0-c595c7d9
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3499 [updatecli] update elastic stack version for testing 8.7.2-dd4c72f2
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3497 [updatecli] update elastic stack version for testing 8.9.0-2dbf1e1f
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3498 [updatecli] update elastic stack version for testing 8.8.0-867f1c4e
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3500 [updatecli] update elastic stack version for testing 8.9.0-58c0f379
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3504 [updatecli] update elastic stack version for testing 8.7.2-7653c06b
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3507 [updatecli] update elastic stack version for testing 8.7.2-581e1396
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3510 [updatecli] update elastic stack version for testing 8.8.0-49c28bdb
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3508 [updatecli] update elastic stack version for testing 8.9.0-5aea1178
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3509 [updatecli] update elastic stack version for testing 8.7.2-99e4ac2a
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3511 [updatecli] update elastic stack version for testing 8.7.2-738acb99
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3512 [updatecli] update elastic stack version for testing 8.8.0-cc834a5d
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3513 [updatecli] update elastic stack version for testing 8.9.0-9682eb9d
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3514 [updatecli] update elastic stack version for testing 8.9.0-b8c97a52
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3515 [updatecli] update elastic stack version for testing 8.8.0-9524d701
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3518 [updatecli] update elastic stack version for testing 8.7.2-34fb9774
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3516 [updatecli] update elastic stack version for testing 8.9.0-df4abdd6
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3519 [updatecli] update elastic stack version for testing 7.17.11-835d340b
  .ci/Jenkinsfile
  .ci/e2eTestingMacosDaily.groovy
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3524 Change old agent snapshot version to official release
  e2e/_suites/fleet/features/upgrade_agent.feature
Labels: bug, Team:Elastic-Agent, backport-skip

#3523 [updatecli] update elastic stack version for testing 8.9.0-95ded584
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3528 [updatecli] update elastic stack version for testing 8.9.0-0b9c4000
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3530 Updating beats Clusteroles to allow job,daemonset discovery
  e2e/_suites/kubernetes-autodiscover/testdata/templates/elastic-agent.yml.tmpl
  e2e/_suites/kubernetes-autodiscover/testdata/templates/filebeat.yml.tmpl
  e2e/_suites/kubernetes-autodiscover/testdata/templates/heartbeat.yml.tmpl
  e2e/_suites/kubernetes-autodiscover/testdata/templates/metricbeat.yml.tmpl
Labels: bug, backport-skip

#3531 [updatecli] update elastic stack version for testing 8.9.0-3cc641a9
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3532 [updatecli] update elastic stack version for testing 8.9.0-3b0166e4
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip
