Repository elastic/e2e-testing, pull requests merged in 2023-02, with the labels that each got.

#3398 [automation] update elastic stack version for testing 8.7.0-87b130b2
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3400 [automation] update elastic stack version for testing 7.17.9-663e90b2
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3404 [automation] update elastic stack version for testing 8.7.0-1ef3b708
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3405 [automation] update elastic stack version for testing 8.6.2-9fa37b7d
  .ci/Jenkinsfile
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/cloud/docker-compose.yml
  internal/config/compose/services/elastic-agent/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/compose/services/elasticsearch/docker-compose.yml
  internal/config/compose/services/kibana/docker-compose.yml
  internal/config/compose/services/metricbeat/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3411 backport: Add 8.7 branch
  .mergify.yml
Labels: Team:Automation, backport-skip, release

#3410 [automation] update elastic stack version for testing 7.17.10-f1f67132
  .ci/Jenkinsfile
  .ci/e2eTestingMacosDaily.groovy
  .stack-version
  internal/common/defaults.go
  internal/config/compose/profiles/fleet/docker-compose.yml
  internal/config/compose/services/elastic-agent/fleet-server/docker-compose.yml
  internal/config/kubernetes/base/elasticsearch/deployment.yaml
  internal/config/kubernetes/base/fleet-server/deployment.yaml
  internal/config/kubernetes/base/kibana/deployment.yaml
Labels: automation, dependency, backport-skip

#3399 Remove known non-working agent versions
  e2e/_suites/fleet/features/upgrade_agent.feature
Labels: bug, backport-skip

#2862 actions: pre-commit and opentelemetry exporter
  .github/workflows/opentelemetry.yml
  .github/workflows/pre-commit.yml
Labels: backport-skip

#3412 automate: bump elastic stack snapshot
  .ci/bump-elastic-stack-snapshot.yml
  .ci/bump-stack-version.sh
  .github/workflows/bump-elastic-stack-snapshot.yml
Labels: Team:Automation, backport-skip

#3413 updatecli: ensure one branch per release branch
  .ci/bump-elastic-stack-snapshot.yml
Labels: automation, backport-skip

#3414 chore: remove support for feature-arch-v2
  .ci/schedule-daily.groovy
  .github/workflows/sync-branches.yml
Labels: automation, backport-skip
